// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteFrontpageApiV1FilmfrontpageLanguageLanguageData, DeleteFrontpageApiV1FilmfrontpageLanguageLanguageErrors, DeleteFrontpageApiV1FilmfrontpageLanguageLanguageResponses, DeleteFrontpageApiV1SubjectpageSubjectpageIdLanguageLanguageData, DeleteFrontpageApiV1SubjectpageSubjectpageIdLanguageLanguageErrors, DeleteFrontpageApiV1SubjectpageSubjectpageIdLanguageLanguageResponses, GetFrontpageApiV1FilmfrontpageData, GetFrontpageApiV1FilmfrontpageErrors, GetFrontpageApiV1FilmfrontpageResponses, GetFrontpageApiV1FrontpageData, GetFrontpageApiV1FrontpageErrors, GetFrontpageApiV1FrontpageResponses, GetFrontpageApiV1SubjectpageData, GetFrontpageApiV1SubjectpageErrors, GetFrontpageApiV1SubjectpageIdsData, GetFrontpageApiV1SubjectpageIdsErrors, GetFrontpageApiV1SubjectpageIdsResponses, GetFrontpageApiV1SubjectpageResponses, GetFrontpageApiV1SubjectpageSubjectpageIdData, GetFrontpageApiV1SubjectpageSubjectpageIdErrors, GetFrontpageApiV1SubjectpageSubjectpageIdResponses, PatchFrontpageApiV1SubjectpageSubjectpageIdData, PatchFrontpageApiV1SubjectpageSubjectpageIdErrors, PatchFrontpageApiV1SubjectpageSubjectpageIdResponses, PostFrontpageApiV1FilmfrontpageData, PostFrontpageApiV1FilmfrontpageErrors, PostFrontpageApiV1FilmfrontpageResponses, PostFrontpageApiV1FrontpageData, PostFrontpageApiV1FrontpageErrors, PostFrontpageApiV1FrontpageResponses, PostFrontpageApiV1SubjectpageData, PostFrontpageApiV1SubjectpageErrors, PostFrontpageApiV1SubjectpageResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Fetch all subjectpages
 */
export const getFrontpageApiV1Subjectpage = <ThrowOnError extends boolean = false>(options?: Options<GetFrontpageApiV1SubjectpageData, ThrowOnError>): RequestResult<GetFrontpageApiV1SubjectpageResponses, GetFrontpageApiV1SubjectpageErrors, ThrowOnError> => (options?.client ?? client).get<GetFrontpageApiV1SubjectpageResponses, GetFrontpageApiV1SubjectpageErrors, ThrowOnError>({ url: '/frontpage-api/v1/subjectpage', ...options });

/**
 * Create new subject page
 */
export const postFrontpageApiV1Subjectpage = <ThrowOnError extends boolean = false>(options: Options<PostFrontpageApiV1SubjectpageData, ThrowOnError>): RequestResult<PostFrontpageApiV1SubjectpageResponses, PostFrontpageApiV1SubjectpageErrors, ThrowOnError> => (options.client ?? client).post<PostFrontpageApiV1SubjectpageResponses, PostFrontpageApiV1SubjectpageErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/frontpage-api/v1/subjectpage',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Fetch subject pages that matches ids parameter
 */
export const getFrontpageApiV1SubjectpageIds = <ThrowOnError extends boolean = false>(options?: Options<GetFrontpageApiV1SubjectpageIdsData, ThrowOnError>): RequestResult<GetFrontpageApiV1SubjectpageIdsResponses, GetFrontpageApiV1SubjectpageIdsErrors, ThrowOnError> => (options?.client ?? client).get<GetFrontpageApiV1SubjectpageIdsResponses, GetFrontpageApiV1SubjectpageIdsErrors, ThrowOnError>({
    querySerializer: { parameters: { ids: { array: { explode: false } } } },
    url: '/frontpage-api/v1/subjectpage/ids',
    ...options
});

/**
 * Get data to display on a subject page
 */
export const getFrontpageApiV1SubjectpageSubjectpageId = <ThrowOnError extends boolean = false>(options: Options<GetFrontpageApiV1SubjectpageSubjectpageIdData, ThrowOnError>): RequestResult<GetFrontpageApiV1SubjectpageSubjectpageIdResponses, GetFrontpageApiV1SubjectpageSubjectpageIdErrors, ThrowOnError> => (options.client ?? client).get<GetFrontpageApiV1SubjectpageSubjectpageIdResponses, GetFrontpageApiV1SubjectpageSubjectpageIdErrors, ThrowOnError>({ url: '/frontpage-api/v1/subjectpage/{subjectpage-id}', ...options });

/**
 * Update subject page
 */
export const patchFrontpageApiV1SubjectpageSubjectpageId = <ThrowOnError extends boolean = false>(options: Options<PatchFrontpageApiV1SubjectpageSubjectpageIdData, ThrowOnError>): RequestResult<PatchFrontpageApiV1SubjectpageSubjectpageIdResponses, PatchFrontpageApiV1SubjectpageSubjectpageIdErrors, ThrowOnError> => (options.client ?? client).patch<PatchFrontpageApiV1SubjectpageSubjectpageIdResponses, PatchFrontpageApiV1SubjectpageSubjectpageIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/frontpage-api/v1/subjectpage/{subjectpage-id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete language from subject page
 *
 * Delete language from subject page
 */
export const deleteFrontpageApiV1SubjectpageSubjectpageIdLanguageLanguage = <ThrowOnError extends boolean = false>(options: Options<DeleteFrontpageApiV1SubjectpageSubjectpageIdLanguageLanguageData, ThrowOnError>): RequestResult<DeleteFrontpageApiV1SubjectpageSubjectpageIdLanguageLanguageResponses, DeleteFrontpageApiV1SubjectpageSubjectpageIdLanguageLanguageErrors, ThrowOnError> => (options.client ?? client).delete<DeleteFrontpageApiV1SubjectpageSubjectpageIdLanguageLanguageResponses, DeleteFrontpageApiV1SubjectpageSubjectpageIdLanguageLanguageErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/frontpage-api/v1/subjectpage/{subjectpage-id}/language/{language}',
    ...options
});

/**
 * Get data to display on the front page
 */
export const getFrontpageApiV1Frontpage = <ThrowOnError extends boolean = false>(options?: Options<GetFrontpageApiV1FrontpageData, ThrowOnError>): RequestResult<GetFrontpageApiV1FrontpageResponses, GetFrontpageApiV1FrontpageErrors, ThrowOnError> => (options?.client ?? client).get<GetFrontpageApiV1FrontpageResponses, GetFrontpageApiV1FrontpageErrors, ThrowOnError>({ url: '/frontpage-api/v1/frontpage', ...options });

/**
 * Create front page
 */
export const postFrontpageApiV1Frontpage = <ThrowOnError extends boolean = false>(options: Options<PostFrontpageApiV1FrontpageData, ThrowOnError>): RequestResult<PostFrontpageApiV1FrontpageResponses, PostFrontpageApiV1FrontpageErrors, ThrowOnError> => (options.client ?? client).post<PostFrontpageApiV1FrontpageResponses, PostFrontpageApiV1FrontpageErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/frontpage-api/v1/frontpage',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get data to display on the film front page
 */
export const getFrontpageApiV1Filmfrontpage = <ThrowOnError extends boolean = false>(options?: Options<GetFrontpageApiV1FilmfrontpageData, ThrowOnError>): RequestResult<GetFrontpageApiV1FilmfrontpageResponses, GetFrontpageApiV1FilmfrontpageErrors, ThrowOnError> => (options?.client ?? client).get<GetFrontpageApiV1FilmfrontpageResponses, GetFrontpageApiV1FilmfrontpageErrors, ThrowOnError>({ url: '/frontpage-api/v1/filmfrontpage', ...options });

/**
 * Update film front page
 */
export const postFrontpageApiV1Filmfrontpage = <ThrowOnError extends boolean = false>(options: Options<PostFrontpageApiV1FilmfrontpageData, ThrowOnError>): RequestResult<PostFrontpageApiV1FilmfrontpageResponses, PostFrontpageApiV1FilmfrontpageErrors, ThrowOnError> => (options.client ?? client).post<PostFrontpageApiV1FilmfrontpageResponses, PostFrontpageApiV1FilmfrontpageErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/frontpage-api/v1/filmfrontpage',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete language from film front page
 *
 * Delete language from film front page
 */
export const deleteFrontpageApiV1FilmfrontpageLanguageLanguage = <ThrowOnError extends boolean = false>(options: Options<DeleteFrontpageApiV1FilmfrontpageLanguageLanguageData, ThrowOnError>): RequestResult<DeleteFrontpageApiV1FilmfrontpageLanguageLanguageResponses, DeleteFrontpageApiV1FilmfrontpageLanguageLanguageErrors, ThrowOnError> => (options.client ?? client).delete<DeleteFrontpageApiV1FilmfrontpageLanguageLanguageResponses, DeleteFrontpageApiV1FilmfrontpageLanguageLanguageErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/frontpage-api/v1/filmfrontpage/language/{language}',
    ...options
});
