// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AboutFilmSubjectDTO
 */
export type AboutFilmSubjectDTO = {
    title: string;
    description: string;
    visualElement: VisualElementDTO;
    language: string;
};

/**
 * AboutSubjectDTO
 */
export type AboutSubjectDTO = {
    title: string;
    description: string;
    visualElement: VisualElementDTO;
};

/**
 * AllErrors
 */
export type AllErrors = ErrorBody | NotFoundWithSupportedLanguages | ValidationErrorBody;

/**
 * BannerImageDTO
 */
export type BannerImageDTO = {
    mobileUrl?: string;
    mobileId?: number;
    desktopUrl: string;
    desktopId: number;
};

/**
 * ErrorBody
 *
 * Information about an error
 */
export type ErrorBody = {
    /**
     * Code stating the type of error
     */
    code: string;
    /**
     * Description of the error
     */
    description: string;
    /**
     * When the error occurred
     */
    occurredAt: string;
    /**
     * Numeric http status code
     */
    statusCode: number;
};

/**
 * FilmFrontPageDTO
 */
export type FilmFrontPageDTO = {
    name: string;
    about: Array<AboutFilmSubjectDTO>;
    movieThemes: Array<MovieThemeDTO>;
    slideShow: Array<string>;
    article?: string;
    supportedLanguages: Array<string>;
};

/**
 * FrontPageDTO
 *
 * Object containing frontpage data
 */
export type FrontPageDTO = {
    /**
     * Id of the frontpage
     */
    articleId: number;
    /**
     * List of Menu objects
     */
    menu: Array<MenuDTO>;
};

/**
 * MenuDTO
 *
 * The Menu object
 */
export type MenuDTO = {
    /**
     * Id of the article
     */
    articleId: number;
    /**
     * List of submenu objects
     */
    menu: Array<MenuDTO>;
    /**
     * Hide this level in menu
     */
    hideLevel?: boolean;
};

/**
 * MovieThemeDTO
 */
export type MovieThemeDTO = {
    name: Array<MovieThemeNameDTO>;
    movies: Array<string>;
};

/**
 * MovieThemeNameDTO
 */
export type MovieThemeNameDTO = {
    name: string;
    language: string;
};

/**
 * NewOrUpdateBannerImageDTO
 */
export type NewOrUpdateBannerImageDTO = {
    mobileImageId?: number;
    desktopImageId: number;
};

/**
 * NewOrUpdatedAboutSubjectDTO
 */
export type NewOrUpdatedAboutSubjectDTO = {
    title: string;
    description: string;
    language: string;
    visualElement: NewOrUpdatedVisualElementDTO;
};

/**
 * NewOrUpdatedFilmFrontPageDTO
 */
export type NewOrUpdatedFilmFrontPageDTO = {
    name: string;
    about: Array<NewOrUpdatedAboutSubjectDTO>;
    movieThemes: Array<NewOrUpdatedMovieThemeDTO>;
    slideShow: Array<string>;
    article?: string;
};

/**
 * NewOrUpdatedMetaDescriptionDTO
 */
export type NewOrUpdatedMetaDescriptionDTO = {
    metaDescription: string;
    language: string;
};

/**
 * NewOrUpdatedMovieNameDTO
 */
export type NewOrUpdatedMovieNameDTO = {
    name: string;
    language: string;
};

/**
 * NewOrUpdatedMovieThemeDTO
 */
export type NewOrUpdatedMovieThemeDTO = {
    name: Array<NewOrUpdatedMovieNameDTO>;
    movies: Array<string>;
};

/**
 * NewOrUpdatedVisualElementDTO
 */
export type NewOrUpdatedVisualElementDTO = {
    type: string;
    id: string;
    alt?: string;
};

/**
 * NewSubjectPageDTO
 */
export type NewSubjectPageDTO = {
    name: string;
    externalId?: string;
    banner: NewOrUpdateBannerImageDTO;
    about: Array<NewOrUpdatedAboutSubjectDTO>;
    metaDescription: Array<NewOrUpdatedMetaDescriptionDTO>;
    editorsChoices?: Array<string>;
    connectedTo?: Array<string>;
    buildsOn?: Array<string>;
    leadsTo?: Array<string>;
};

/**
 * NotFoundWithSupportedLanguages
 *
 * Information about an error
 */
export type NotFoundWithSupportedLanguages = {
    /**
     * Code stating the type of error
     */
    code: string;
    /**
     * Description of the error
     */
    description: string;
    /**
     * When the error occurred
     */
    occurredAt: string;
    /**
     * List of supported languages
     */
    supportedLanguages?: Array<string>;
    /**
     * Numeric http status code
     */
    statusCode: number;
};

/**
 * PopularArticleDTO
 */
export type PopularArticleDTO = {
    contextId: string;
    numHits: number;
};

/**
 * SubjectPageDTO
 */
export type SubjectPageDTO = {
    id: number;
    name: string;
    banner: BannerImageDTO;
    about?: AboutSubjectDTO;
    metaDescription?: string;
    editorsChoices: Array<string>;
    supportedLanguages: Array<string>;
    connectedTo: Array<string>;
    buildsOn: Array<string>;
    leadsTo: Array<string>;
    popularArticles: Array<PopularArticleDTO>;
};

/**
 * UpdatedSubjectPageDTO
 */
export type UpdatedSubjectPageDTO = {
    name?: string;
    externalId?: string;
    banner?: NewOrUpdateBannerImageDTO;
    about?: Array<NewOrUpdatedAboutSubjectDTO>;
    metaDescription?: Array<NewOrUpdatedMetaDescriptionDTO>;
    editorsChoices?: Array<string>;
    connectedTo?: Array<string>;
    buildsOn?: Array<string>;
    leadsTo?: Array<string>;
};

/**
 * ValidationErrorBody
 *
 * Information about an error
 */
export type ValidationErrorBody = {
    /**
     * Code stating the type of error
     */
    code: string;
    /**
     * Description of the error
     */
    description: string;
    /**
     * When the error occurred
     */
    occurredAt: string;
    /**
     * List of validation messages
     */
    messages?: Array<ValidationMessage>;
    /**
     * Numeric http status code
     */
    statusCode: number;
};

/**
 * ValidationMessage
 *
 * A message describing a validation error on a specific field
 */
export type ValidationMessage = {
    /**
     * The field the error occured in
     */
    field: string;
    /**
     * The validation message
     */
    message: string;
};

/**
 * VisualElementDTO
 */
export type VisualElementDTO = {
    type: string;
    url: string;
    alt?: string;
};

export type GetFrontpageApiV1SubjectpageData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The page number of the search hits to display.
         */
        page?: number;
        /**
         * The number of search hits to display for each page.
         */
        'page-size'?: number;
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
    };
    url: '/frontpage-api/v1/subjectpage';
};

export type GetFrontpageApiV1SubjectpageErrors = {
    400: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetFrontpageApiV1SubjectpageError = GetFrontpageApiV1SubjectpageErrors[keyof GetFrontpageApiV1SubjectpageErrors];

export type GetFrontpageApiV1SubjectpageResponses = {
    200: Array<SubjectPageDTO>;
};

export type GetFrontpageApiV1SubjectpageResponse = GetFrontpageApiV1SubjectpageResponses[keyof GetFrontpageApiV1SubjectpageResponses];

export type PostFrontpageApiV1SubjectpageData = {
    body: NewSubjectPageDTO;
    path?: never;
    query?: never;
    url: '/frontpage-api/v1/subjectpage';
};

export type PostFrontpageApiV1SubjectpageErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PostFrontpageApiV1SubjectpageError = PostFrontpageApiV1SubjectpageErrors[keyof PostFrontpageApiV1SubjectpageErrors];

export type PostFrontpageApiV1SubjectpageResponses = {
    200: SubjectPageDTO;
};

export type PostFrontpageApiV1SubjectpageResponse = PostFrontpageApiV1SubjectpageResponses[keyof PostFrontpageApiV1SubjectpageResponses];

export type GetFrontpageApiV1SubjectpageIdsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return only subject pages that have one of the provided ids. To provide multiple ids, separate by comma (,).
         */
        ids?: Array<number>;
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
        /**
         * The number of search hits to display for each page.
         */
        'page-size'?: number;
        /**
         * The page number of the search hits to display.
         */
        page?: number;
    };
    url: '/frontpage-api/v1/subjectpage/ids';
};

export type GetFrontpageApiV1SubjectpageIdsErrors = {
    400: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetFrontpageApiV1SubjectpageIdsError = GetFrontpageApiV1SubjectpageIdsErrors[keyof GetFrontpageApiV1SubjectpageIdsErrors];

export type GetFrontpageApiV1SubjectpageIdsResponses = {
    200: Array<SubjectPageDTO>;
};

export type GetFrontpageApiV1SubjectpageIdsResponse = GetFrontpageApiV1SubjectpageIdsResponses[keyof GetFrontpageApiV1SubjectpageIdsResponses];

export type GetFrontpageApiV1SubjectpageSubjectpageIdData = {
    body?: never;
    path: {
        /**
         * The subjectpage id
         */
        'subjectpage-id': number;
    };
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
    };
    url: '/frontpage-api/v1/subjectpage/{subjectpage-id}';
};

export type GetFrontpageApiV1SubjectpageSubjectpageIdErrors = {
    400: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetFrontpageApiV1SubjectpageSubjectpageIdError = GetFrontpageApiV1SubjectpageSubjectpageIdErrors[keyof GetFrontpageApiV1SubjectpageSubjectpageIdErrors];

export type GetFrontpageApiV1SubjectpageSubjectpageIdResponses = {
    200: SubjectPageDTO;
};

export type GetFrontpageApiV1SubjectpageSubjectpageIdResponse = GetFrontpageApiV1SubjectpageSubjectpageIdResponses[keyof GetFrontpageApiV1SubjectpageSubjectpageIdResponses];

export type PatchFrontpageApiV1SubjectpageSubjectpageIdData = {
    body: UpdatedSubjectPageDTO;
    path: {
        /**
         * The subjectpage id
         */
        'subjectpage-id': number;
    };
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
    };
    url: '/frontpage-api/v1/subjectpage/{subjectpage-id}';
};

export type PatchFrontpageApiV1SubjectpageSubjectpageIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PatchFrontpageApiV1SubjectpageSubjectpageIdError = PatchFrontpageApiV1SubjectpageSubjectpageIdErrors[keyof PatchFrontpageApiV1SubjectpageSubjectpageIdErrors];

export type PatchFrontpageApiV1SubjectpageSubjectpageIdResponses = {
    200: SubjectPageDTO;
};

export type PatchFrontpageApiV1SubjectpageSubjectpageIdResponse = PatchFrontpageApiV1SubjectpageSubjectpageIdResponses[keyof PatchFrontpageApiV1SubjectpageSubjectpageIdResponses];

export type DeleteFrontpageApiV1SubjectpageSubjectpageIdLanguageLanguageData = {
    body?: never;
    path: {
        /**
         * The subjectpage id
         */
        'subjectpage-id': number;
        /**
         * The ISO 639-1 language code describing language.
         */
        language: string;
    };
    query?: never;
    url: '/frontpage-api/v1/subjectpage/{subjectpage-id}/language/{language}';
};

export type DeleteFrontpageApiV1SubjectpageSubjectpageIdLanguageLanguageErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type DeleteFrontpageApiV1SubjectpageSubjectpageIdLanguageLanguageError = DeleteFrontpageApiV1SubjectpageSubjectpageIdLanguageLanguageErrors[keyof DeleteFrontpageApiV1SubjectpageSubjectpageIdLanguageLanguageErrors];

export type DeleteFrontpageApiV1SubjectpageSubjectpageIdLanguageLanguageResponses = {
    200: SubjectPageDTO;
};

export type DeleteFrontpageApiV1SubjectpageSubjectpageIdLanguageLanguageResponse = DeleteFrontpageApiV1SubjectpageSubjectpageIdLanguageLanguageResponses[keyof DeleteFrontpageApiV1SubjectpageSubjectpageIdLanguageLanguageResponses];

export type GetFrontpageApiV1FrontpageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/frontpage-api/v1/frontpage';
};

export type GetFrontpageApiV1FrontpageErrors = {
    400: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetFrontpageApiV1FrontpageError = GetFrontpageApiV1FrontpageErrors[keyof GetFrontpageApiV1FrontpageErrors];

export type GetFrontpageApiV1FrontpageResponses = {
    200: FrontPageDTO;
};

export type GetFrontpageApiV1FrontpageResponse = GetFrontpageApiV1FrontpageResponses[keyof GetFrontpageApiV1FrontpageResponses];

export type PostFrontpageApiV1FrontpageData = {
    body: FrontPageDTO;
    path?: never;
    query?: never;
    url: '/frontpage-api/v1/frontpage';
};

export type PostFrontpageApiV1FrontpageErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PostFrontpageApiV1FrontpageError = PostFrontpageApiV1FrontpageErrors[keyof PostFrontpageApiV1FrontpageErrors];

export type PostFrontpageApiV1FrontpageResponses = {
    200: FrontPageDTO;
};

export type PostFrontpageApiV1FrontpageResponse = PostFrontpageApiV1FrontpageResponses[keyof PostFrontpageApiV1FrontpageResponses];

export type GetFrontpageApiV1FilmfrontpageData = {
    body?: never;
    path?: never;
    query?: {
        language?: string;
    };
    url: '/frontpage-api/v1/filmfrontpage';
};

export type GetFrontpageApiV1FilmfrontpageErrors = {
    400: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetFrontpageApiV1FilmfrontpageError = GetFrontpageApiV1FilmfrontpageErrors[keyof GetFrontpageApiV1FilmfrontpageErrors];

export type GetFrontpageApiV1FilmfrontpageResponses = {
    200: FilmFrontPageDTO;
};

export type GetFrontpageApiV1FilmfrontpageResponse = GetFrontpageApiV1FilmfrontpageResponses[keyof GetFrontpageApiV1FilmfrontpageResponses];

export type PostFrontpageApiV1FilmfrontpageData = {
    body: NewOrUpdatedFilmFrontPageDTO;
    path?: never;
    query?: never;
    url: '/frontpage-api/v1/filmfrontpage';
};

export type PostFrontpageApiV1FilmfrontpageErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    422: AllErrors;
    default: AllErrors;
};

export type PostFrontpageApiV1FilmfrontpageError = PostFrontpageApiV1FilmfrontpageErrors[keyof PostFrontpageApiV1FilmfrontpageErrors];

export type PostFrontpageApiV1FilmfrontpageResponses = {
    200: FilmFrontPageDTO;
};

export type PostFrontpageApiV1FilmfrontpageResponse = PostFrontpageApiV1FilmfrontpageResponses[keyof PostFrontpageApiV1FilmfrontpageResponses];

export type DeleteFrontpageApiV1FilmfrontpageLanguageLanguageData = {
    body?: never;
    path: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language: string;
    };
    query?: never;
    url: '/frontpage-api/v1/filmfrontpage/language/{language}';
};

export type DeleteFrontpageApiV1FilmfrontpageLanguageLanguageErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type DeleteFrontpageApiV1FilmfrontpageLanguageLanguageError = DeleteFrontpageApiV1FilmfrontpageLanguageLanguageErrors[keyof DeleteFrontpageApiV1FilmfrontpageLanguageLanguageErrors];

export type DeleteFrontpageApiV1FilmfrontpageLanguageLanguageResponses = {
    200: FilmFrontPageDTO;
};

export type DeleteFrontpageApiV1FilmfrontpageLanguageLanguageResponse = DeleteFrontpageApiV1FilmfrontpageLanguageLanguageResponses[keyof DeleteFrontpageApiV1FilmfrontpageLanguageLanguageResponses];
