// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AddMultipleNotesDTO
 *
 * Information about notes to add to drafts
 */
export type AddMultipleNotesDTO = {
    /**
     * Objects for which notes should be added to which drafts
     */
    data: Array<AddNoteDTO>;
};

/**
 * AddNoteDTO
 *
 * Information containing new notes and which draft to add them to
 */
export type AddNoteDTO = {
    /**
     * Id of the draft to add notes to
     */
    draftId: number;
    /**
     * Notes to add to the draft
     */
    notes: Array<string>;
};

/**
 * AllErrors
 */
export type AllErrors = ErrorBody | NotFoundWithSupportedLanguages | ValidationErrorBody;

/**
 * ArticleContentDTO
 *
 * The content of the article in available languages
 */
export type ArticleContentDTO = {
    /**
     * The html content
     */
    content: string;
    /**
     * ISO 639-1 code that represents the language used in the content
     */
    language: string;
};

/**
 * ArticleDTO
 *
 * Information about the article
 */
export type ArticleDTO = {
    /**
     * The unique id of the article
     */
    id: number;
    /**
     * Link to article on old platform
     */
    oldNdlaUrl?: string;
    /**
     * The revision number for the article
     */
    revision: number;
    /**
     * The status of this article
     */
    status: StatusDTO;
    /**
     * Available titles for the article
     */
    title?: ArticleTitleDTO;
    content?: ArticleContentDTO;
    copyright?: DraftCopyrightDTO;
    tags?: ArticleTagDTO;
    /**
     * Required libraries in order to render the article
     */
    requiredLibraries: Array<RequiredLibraryDTO>;
    visualElement?: VisualElementDTO;
    introduction?: ArticleIntroductionDTO;
    metaDescription?: ArticleMetaDescriptionDTO;
    metaImage?: ArticleMetaImageDTO;
    /**
     * When the article was created
     */
    created: string;
    /**
     * When the article was last updated
     */
    updated: string;
    /**
     * By whom the article was last updated
     */
    updatedBy: string;
    /**
     * When the article was last published
     */
    published?: string;
    /**
     * Revision date of the article
     */
    revised: string;
    /**
     * The type of article this is. Possible values are frontpage-article, standard, topic-article
     */
    articleType: string;
    /**
     * The languages this article supports
     */
    supportedLanguages: Array<string>;
    /**
     * The notes for this article draft
     */
    notes: Array<EditorNoteDTO>;
    /**
     * The labels attached to this article; meant for editors.
     */
    editorLabels: Array<string>;
    /**
     * A list of codes from GREP API connected to the article
     */
    grepCodes: Array<string>;
    /**
     * A list of conceptIds connected to the article
     */
    conceptIds: Array<number>;
    /**
     * Value that dictates who gets to see the article. Possible values are: everyone/teacher
     */
    availability: string;
    /**
     * A list of content related to the article
     */
    relatedContent: Array<RelatedContentLinkDTO | number>;
    /**
     * A list of revisions planned for the article
     */
    revisions: Array<RevisionMetaDTO>;
    responsible?: ResponsibleDTO;
    /**
     * The path to the frontpage article
     */
    slug?: string;
    /**
     * Information about comments attached to the article
     */
    comments: Array<CommentDTO>;
    priority: Priority;
    /**
     * If the article has been edited after last status or responsible change
     */
    started: boolean;
    qualityEvaluation?: QualityEvaluationDTO;
    disclaimer?: DisclaimerDTO;
    /**
     * Traits extracted from the article content
     */
    traits: Array<ArticleTrait>;
};

/**
 * ArticleIntroductionDTO
 *
 * An introduction for the article
 */
export type ArticleIntroductionDTO = {
    /**
     * The introduction content
     */
    introduction: string;
    /**
     * The html introduction content
     */
    htmlIntroduction: string;
    /**
     * The ISO 639-1 language code describing which article translation this introduction belongs to
     */
    language: string;
};

/**
 * ArticleMetaDescriptionDTO
 *
 * Meta description for the article
 */
export type ArticleMetaDescriptionDTO = {
    /**
     * The meta description
     */
    metaDescription: string;
    /**
     * The ISO 639-1 language code describing which article translation this meta description belongs to
     */
    language: string;
};

/**
 * ArticleMetaImageDTO
 *
 * Meta image for the article
 */
export type ArticleMetaImageDTO = {
    /**
     * The meta image
     */
    url: string;
    /**
     * The meta image alt text
     */
    alt: string;
    /**
     * The ISO 639-1 language code describing which article translation this meta image belongs to
     */
    language: string;
};

/**
 * ArticleRevisionHistoryDTO
 *
 * Information about article revision history
 */
export type ArticleRevisionHistoryDTO = {
    /**
     * The revisions of an article, with the latest revision being the first in the list
     */
    revisions: Array<ArticleDTO>;
    /**
     * Whether or not the current revision is safe to delete
     */
    canDeleteCurrentRevision: boolean;
};

/**
 * ArticleSearchParamsDTO
 *
 * The search parameters
 */
export type ArticleSearchParamsDTO = {
    /**
     * The search query
     */
    query?: string;
    /**
     * The ISO 639-1 language code describing language used in query-params
     */
    language?: string;
    /**
     * Return only articles with provided license. Specifying 'all' gives all articles regardless of license.
     */
    license?: string;
    /**
     * The page number of the search hits to display.
     */
    page?: number;
    /**
     * The number of search hits to display for each page.
     */
    pageSize?: number;
    /**
     * Return only articles that have one of the provided ids
     */
    ids?: Array<number>;
    /**
     * Return only articles of specific type(s)
     */
    articleTypes?: Array<string>;
    sort?: Sort;
    /**
     * A search context retrieved from the response header of a previous search.
     */
    scrollId?: string;
    /**
     * Fallback to some existing language if language is specified.
     */
    fallback?: boolean;
    /**
     * Return only articles containing codes from GREP API
     */
    grepCodes?: Array<string>;
};

/**
 * ArticleSearchResultDTO
 *
 * Information about search-results
 */
export type ArticleSearchResultDTO = {
    /**
     * The total number of articles matching this query
     */
    totalCount: number;
    /**
     * For which page results are shown from
     */
    page?: number;
    /**
     * The number of results per page
     */
    pageSize: number;
    /**
     * The search results
     */
    results: Array<ArticleSummaryDTO>;
};

/**
 * ArticleSummaryDTO
 *
 * Short summary of information about the article
 */
export type ArticleSummaryDTO = {
    /**
     * The unique id of the article
     */
    id: number;
    /**
     * The title of the article
     */
    title: ArticleTitleDTO;
    visualElement?: VisualElementDTO;
    introduction?: ArticleIntroductionDTO;
    /**
     * The full url to where the complete information about the article can be found
     */
    url: string;
    /**
     * Describes the license of the article
     */
    license: string;
    /**
     * The type of article this is. Possible values are frontpage-article, standard, topic-article
     */
    articleType: string;
    /**
     * A list of available languages for this audio
     */
    supportedLanguages: Array<string>;
    tags?: ArticleTagDTO;
    /**
     * The notes for this draft article
     */
    notes: Array<string>;
    /**
     * The users saved for this draft article
     */
    users: Array<string>;
    /**
     * The codes from GREP API registered for this draft article
     */
    grepCodes: Array<string>;
    /**
     * The status of this article
     */
    status: StatusDTO;
    /**
     * When the article was last updated
     */
    updated: string;
    /**
     * Traits extracted from the article content
     */
    traits: Array<ArticleTrait>;
};

/**
 * ArticleTagDTO
 *
 * Searchable tags for the article
 */
export type ArticleTagDTO = {
    /**
     * The searchable tag.
     */
    tags: Array<string>;
    /**
     * ISO 639-1 code that represents the language used in tag
     */
    language: string;
};

/**
 * ArticleTitleDTO
 */
export type ArticleTitleDTO = {
    /**
     * The freetext title of the article
     */
    title: string;
    /**
     * The freetext html title of the article
     */
    htmlTitle: string;
    /**
     * ISO 639-1 code that represents the language used in title
     */
    language: string;
};

/**
 * ArticleTrait
 */
export type ArticleTrait = 'AUDIO' | 'H5P' | 'INTERACTIVE' | 'PODCAST' | 'VIDEO';

/**
 * AuthorDTO
 *
 * Information about an author
 */
export type AuthorDTO = {
    type: ContributorType;
    /**
     * The name of the of the author
     */
    name: string;
};

/**
 * CommentDTO
 *
 * Information about a comment attached to an article
 */
export type CommentDTO = {
    /**
     * Id of the comment
     */
    id: string;
    /**
     * Content of the comment
     */
    content: string;
    /**
     * When the comment was created
     */
    created: string;
    /**
     * When the comment was last updated
     */
    updated: string;
    /**
     * If the comment is open or closed
     */
    isOpen: boolean;
    /**
     * If the comment is solved or not
     */
    solved: boolean;
};

/**
 * ContentIdDTO
 *
 * Id for a single Article
 */
export type ContentIdDTO = {
    /**
     * The unique id of the article
     */
    id: number;
};

/**
 * ContributorType
 *
 * The description of the author. Eg. Photographer or Supplier
 */
export type ContributorType = 'artist' | 'cowriter' | 'compiler' | 'composer' | 'correction' | 'director' | 'distributor' | 'editorial' | 'facilitator' | 'idea' | 'illustrator' | 'linguistic' | 'originator' | 'photographer' | 'processor' | 'publisher' | 'reader' | 'rightsholder' | 'scriptwriter' | 'supplier' | 'translator' | 'writer';

/**
 * DisclaimerDTO
 *
 * The disclaimer of the article
 */
export type DisclaimerDTO = {
    /**
     * The freetext html content of the disclaimer
     */
    disclaimer: string;
    /**
     * ISO 639-1 code that represents the language used in the disclaimer
     */
    language: string;
};

/**
 * DraftCopyrightDTO
 *
 * Describes the copyright information for the article
 */
export type DraftCopyrightDTO = {
    /**
     * Describes the license of the article
     */
    license?: LicenseDTO;
    /**
     * Reference to where the article is procured
     */
    origin?: string;
    /**
     * List of creators
     */
    creators: Array<AuthorDTO>;
    /**
     * List of processors
     */
    processors: Array<AuthorDTO>;
    /**
     * List of rightsholders
     */
    rightsholders: Array<AuthorDTO>;
    /**
     * Date from which the copyright is valid
     */
    validFrom?: string;
    /**
     * Date to which the copyright is valid
     */
    validTo?: string;
    /**
     * Whether or not the content has been processed
     */
    processed: boolean;
};

/**
 * EditorNoteDTO
 *
 * Information about the editorial notes
 */
export type EditorNoteDTO = {
    /**
     * Editorial note
     */
    note: string;
    /**
     * User which saved the note
     */
    user: string;
    /**
     * Status of article at saved time
     */
    status: StatusDTO;
    /**
     * Timestamp of when note was saved
     */
    timestamp: string;
};

/**
 * ErrorBody
 *
 * Information about an error
 */
export type ErrorBody = {
    /**
     * Code stating the type of error
     */
    code: string;
    /**
     * Description of the error
     */
    description: string;
    /**
     * When the error occurred
     */
    occurredAt: string;
    /**
     * Numeric http status code
     */
    statusCode: number;
};

/**
 * FileForm
 */
export type FileForm = {
    file: Blob | File;
};

/**
 * Grade
 *
 * The grade (1-5) of the article
 */
export type Grade = 1 | 2 | 3 | 4 | 5;

/**
 * GrepCodesSearchResultDTO
 *
 * Information and metadata about codes from GREP API
 */
export type GrepCodesSearchResultDTO = {
    /**
     * The total number of codes from GREP API matching this query
     */
    totalCount: number;
    /**
     * For which page results are shown from
     */
    page: number;
    /**
     * The number of results per page
     */
    pageSize: number;
    /**
     * The search results
     */
    results: Array<string>;
};

/**
 * LicenseDTO
 */
export type LicenseDTO = {
    /**
     * The name of the license
     */
    license: string;
    /**
     * Description of the license
     */
    description?: string;
    /**
     * Url to where the license can be found
     */
    url?: string;
};

/**
 * Map_List_String
 */
export type Map_List_String = {
    [key: string]: Array<string>;
};

/**
 * MultiPartialPublishResultDTO
 *
 * A list of articles that were partial published to article-api
 */
export type MultiPartialPublishResultDTO = {
    /**
     * Successful ids
     */
    successes: Array<number>;
    /**
     * Failed ids with error messages
     */
    failures: Array<PartialPublishFailureDTO>;
};

/**
 * NewArticleDTO
 *
 * Information about the article
 */
export type NewArticleDTO = {
    /**
     * The chosen language
     */
    language: string;
    /**
     * The title of the article
     */
    title: string;
    /**
     * The date the article is published
     */
    published?: string;
    /**
     * The revision date of the article
     */
    revised?: string;
    /**
     * The content of the article
     */
    content?: string;
    /**
     * Searchable tags
     */
    tags?: Array<string>;
    /**
     * An introduction
     */
    introduction?: string;
    /**
     * A meta description
     */
    metaDescription?: string;
    /**
     * Meta image for the article
     */
    metaImage?: NewArticleMetaImageDTO;
    /**
     * A visual element for the article. May be anything from an image to a video or H5P
     */
    visualElement?: string;
    copyright?: DraftCopyrightDTO;
    /**
     * Required libraries in order to render the article
     */
    requiredLibraries?: Array<RequiredLibraryDTO>;
    /**
     * The type of article this is. Possible values are frontpage-article, standard, topic-article
     */
    articleType: string;
    /**
     * The notes for this article draft
     */
    notes?: Array<string>;
    /**
     * The labels attached to this article; meant for editors.
     */
    editorLabels?: Array<string>;
    /**
     * A list of codes from GREP API connected to the article
     */
    grepCodes?: Array<string>;
    /**
     * A list of conceptIds connected to the article
     */
    conceptIds?: Array<number>;
    /**
     * Value that dictates who gets to see the article. Possible values are: everyone/teacher
     */
    availability?: string;
    /**
     * A list of content related to the article
     */
    relatedContent?: Array<RelatedContentLinkDTO | number>;
    /**
     * An object describing a future revision
     */
    revisionMeta?: Array<RevisionMetaDTO>;
    /**
     * NDLA ID representing the editor responsible for this article
     */
    responsibleId?: string;
    /**
     * The path to the frontpage article
     */
    slug?: string;
    /**
     * Information about a comment attached to an article
     */
    comments?: Array<NewCommentDTO>;
    priority?: Priority;
    qualityEvaluation?: QualityEvaluationDTO;
    /**
     * The disclaimer of the article
     */
    disclaimer?: string;
};

/**
 * NewArticleMetaImageDTO
 */
export type NewArticleMetaImageDTO = {
    /**
     * The image-api id of the meta image
     */
    id: string;
    /**
     * The alt text of the meta image
     */
    alt: string;
};

/**
 * NewCommentDTO
 *
 * Information about a comment attached to an article
 */
export type NewCommentDTO = {
    /**
     * Content of the comment
     */
    content: string;
    /**
     * If the comment is open or closed
     */
    isOpen?: boolean;
};

/**
 * NotFoundWithSupportedLanguages
 *
 * Information about an error
 */
export type NotFoundWithSupportedLanguages = {
    /**
     * Code stating the type of error
     */
    code: string;
    /**
     * Description of the error
     */
    description: string;
    /**
     * When the error occurred
     */
    occurredAt: string;
    /**
     * List of supported languages
     */
    supportedLanguages?: Array<string>;
    /**
     * Numeric http status code
     */
    statusCode: number;
};

/**
 * PartialArticleFieldsDTO
 */
export type PartialArticleFieldsDTO = 'availability' | 'grepCodes' | 'license' | 'metaDescription' | 'relatedContent' | 'tags' | 'revisionDate' | 'revised';

/**
 * PartialBulkArticlesDTO
 *
 * Partial data about articles to publish in bulk
 */
export type PartialBulkArticlesDTO = {
    /**
     * A list of article ids to partially publish
     */
    articleIds: Array<number>;
    /**
     * A list of fields that should be partially published
     */
    fields: Array<PartialArticleFieldsDTO>;
};

/**
 * PartialPublishFailureDTO
 *
 * Single failed result
 */
export type PartialPublishFailureDTO = {
    /**
     * Id of the article in question
     */
    id: number;
    /**
     * Error message
     */
    message: string;
};

/**
 * Priority
 *
 * If the article should be prioritized. Possible values are prioritized, on-hold, unspecified
 */
export type Priority = 'prioritized' | 'on-hold' | 'unspecified';

/**
 * QualityEvaluationDTO
 *
 * The quality evaluation of the article. Consist of a score from 1 to 5 and a comment.
 */
export type QualityEvaluationDTO = {
    grade: Grade;
    /**
     * Note explaining the score
     */
    note?: string;
};

/**
 * RelatedContentLinkDTO
 *
 * External link related to the article
 */
export type RelatedContentLinkDTO = {
    /**
     * Title of the article
     */
    title: string;
    /**
     * The url to where the article can be viewed
     */
    url: string;
};

/**
 * RequiredLibraryDTO
 *
 * Information about a library required to render the article
 */
export type RequiredLibraryDTO = {
    /**
     * The type of the library. E.g. CSS or JavaScript
     */
    mediaType: string;
    /**
     * The name of the library
     */
    name: string;
    /**
     * The full url to where the library can be downloaded
     */
    url: string;
};

/**
 * ResponsibleDTO
 *
 * Object with data representing the editor responsible for this article
 */
export type ResponsibleDTO = {
    /**
     * NDLA ID of responsible editor
     */
    responsibleId: string;
    /**
     * Date of when the responsible editor was last updated
     */
    lastUpdated: string;
};

/**
 * RevisionMetaDTO
 *
 * Information about the editorial notes
 */
export type RevisionMetaDTO = {
    /**
     * An unique uuid of the revision. If none supplied, one is generated.
     */
    id?: string;
    /**
     * A date on which the article would need to be revised
     */
    revisionDate: string;
    /**
     * Notes to keep track of what needs to happen before revision
     */
    note: string;
    /**
     * Status of a revision, either 'revised' or 'needs-revision'
     */
    status: string;
};

/**
 * SavedSearchDTO
 *
 * Information about saved search
 */
export type SavedSearchDTO = {
    /**
     * The search url
     */
    searchUrl: string;
    /**
     * The search phrase
     */
    searchPhrase: string;
};

/**
 * Sort
 *
 * The sorting used on results. Default is by -relevance.
 */
export type Sort = '-relevance' | 'relevance' | '-title' | 'title' | '-lastUpdated' | 'lastUpdated' | '-id' | 'id';

/**
 * StatusDTO
 */
export type StatusDTO = {
    /**
     * The current status of the article
     */
    current: string;
    /**
     * Previous statuses this article has been in
     */
    other: Array<string>;
};

/**
 * TagsSearchResultDTO
 *
 * Information about tags-search-results
 */
export type TagsSearchResultDTO = {
    /**
     * The total number of tags matching this query
     */
    totalCount: number;
    /**
     * For which page results are shown from
     */
    page: number;
    /**
     * The number of results per page
     */
    pageSize: number;
    /**
     * The chosen search language
     */
    language: string;
    /**
     * The search results
     */
    results: Array<string>;
};

/**
 * UpdatedArticleDTO
 *
 * Information about the article
 */
export type UpdatedArticleDTO = {
    /**
     * The revision number for the article
     */
    revision: number;
    /**
     * The chosen language
     */
    language?: string;
    /**
     * The title of the article
     */
    title?: string;
    /**
     * The status of the article
     */
    status?: string;
    /**
     * The date the article is published
     */
    published?: string;
    /**
     * The revision date of the article
     */
    revised?: string;
    /**
     * The content of the article
     */
    content?: string;
    /**
     * Searchable tags
     */
    tags?: Array<string>;
    /**
     * An introduction
     */
    introduction?: string;
    /**
     * A meta description
     */
    metaDescription?: string;
    /**
     * An image-api ID for the article meta image
     */
    metaImage?: NewArticleMetaImageDTO | null;
    /**
     * A visual element for the article. May be anything from an image to a video or H5P
     */
    visualElement?: string;
    copyright?: DraftCopyrightDTO;
    /**
     * Required libraries in order to render the article
     */
    requiredLibraries?: Array<RequiredLibraryDTO>;
    /**
     * The type of article this is. Possible values are frontpage-article, standard, topic-article
     */
    articleType?: string;
    /**
     * The notes for this article draft
     */
    notes?: Array<string>;
    /**
     * The labels attached to this article; meant for editors.
     */
    editorLabels?: Array<string>;
    /**
     * A list of codes from GREP API connected to the article
     */
    grepCodes?: Array<string>;
    /**
     * A list of conceptIds connected to the article
     */
    conceptIds?: Array<number>;
    /**
     * Stores the new article as a separate version. Useful when making big changes that should be revertable.
     */
    createNewVersion?: boolean;
    /**
     * Value that dictates who gets to see the article. Possible values are: everyone/teacher
     */
    availability?: string;
    /**
     * A list of content related to the article
     */
    relatedContent?: Array<RelatedContentLinkDTO | number>;
    /**
     * A list of all revisions of the article
     */
    revisionMeta?: Array<RevisionMetaDTO>;
    /**
     * NDLA ID representing the editor responsible for this article
     */
    responsibleId?: string | null;
    /**
     * The path to the frontpage article
     */
    slug?: string;
    /**
     * Information about a comment attached to an article
     */
    comments?: Array<UpdatedCommentDTO>;
    priority?: Priority;
    qualityEvaluation?: QualityEvaluationDTO;
    /**
     * The disclaimer of the article
     */
    disclaimer?: string;
};

/**
 * UpdatedCommentDTO
 *
 * Information about a comment attached to an article
 */
export type UpdatedCommentDTO = {
    /**
     * Id of the comment
     */
    id?: string;
    /**
     * Content of the comment
     */
    content: string;
    /**
     * If the comment is open or closed
     */
    isOpen?: boolean;
    /**
     * If the comment is solved or not
     */
    solved?: boolean;
};

/**
 * UpdatedUserDataDTO
 *
 * Information about user data
 */
export type UpdatedUserDataDTO = {
    /**
     * User's saved searches
     */
    savedSearches?: Array<SavedSearchDTO>;
    /**
     * User's last edited articles
     */
    latestEditedArticles?: Array<string>;
    /**
     * User's last edited concepts
     */
    latestEditedConcepts?: Array<string>;
    /**
     * User's last edited learningpaths
     */
    latestEditedLearningpaths?: Array<string>;
    /**
     * User's favorite subjects
     */
    favoriteSubjects?: Array<string>;
};

/**
 * UploadedFileDTO
 *
 * Information about the uploaded file
 */
export type UploadedFileDTO = {
    /**
     * Uploaded file's basename
     */
    filename: string;
    /**
     * Uploaded file's mime type
     */
    mime: string;
    /**
     * Uploaded file's file extension
     */
    extension: string;
    /**
     * Full path of uploaded file
     */
    path: string;
};

/**
 * UserDataDTO
 *
 * Information about user data
 */
export type UserDataDTO = {
    /**
     * The auth0 id of the user
     */
    userId: string;
    /**
     * User's saved searches
     */
    savedSearches?: Array<SavedSearchDTO>;
    /**
     * User's last edited articles
     */
    latestEditedArticles?: Array<string>;
    /**
     * User's last edited concepts
     */
    latestEditedConcepts?: Array<string>;
    /**
     * User's last edited learningpaths
     */
    latestEditedLearningpaths?: Array<string>;
    /**
     * User's favorite subjects
     */
    favoriteSubjects?: Array<string>;
};

/**
 * ValidationErrorBody
 *
 * Information about an error
 */
export type ValidationErrorBody = {
    /**
     * Code stating the type of error
     */
    code: string;
    /**
     * Description of the error
     */
    description: string;
    /**
     * When the error occurred
     */
    occurredAt: string;
    /**
     * List of validation messages
     */
    messages?: Array<ValidationMessage>;
    /**
     * Numeric http status code
     */
    statusCode: number;
};

/**
 * ValidationMessage
 *
 * A message describing a validation error on a specific field
 */
export type ValidationMessage = {
    /**
     * The field the error occured in
     */
    field: string;
    /**
     * The validation message
     */
    message: string;
};

/**
 * VisualElementDTO
 *
 * A visual element article
 */
export type VisualElementDTO = {
    /**
     * Html containing the visual element. May contain any legal html element, including the embed-tag
     */
    visualElement: string;
    /**
     * The ISO 639-1 language code describing which article translation this visual element belongs to
     */
    language: string;
};

export type GetDraftApiV1DraftsLicensesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A filter to remove a specific entry
         */
        filterNot?: string;
        /**
         * A filter to include a specific entry
         */
        filter?: string;
    };
    url: '/draft-api/v1/drafts/licenses';
};

export type GetDraftApiV1DraftsLicensesErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetDraftApiV1DraftsLicensesError = GetDraftApiV1DraftsLicensesErrors[keyof GetDraftApiV1DraftsLicensesErrors];

export type GetDraftApiV1DraftsLicensesResponses = {
    200: Array<LicenseDTO>;
};

export type GetDraftApiV1DraftsLicensesResponse = GetDraftApiV1DraftsLicensesResponses[keyof GetDraftApiV1DraftsLicensesResponses];

export type GetDraftApiV1DraftsTagSearchData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return only articles with content matching the specified query.
         */
        query?: string;
        /**
         * The number of search hits to display for each page.
         */
        'page-size'?: number;
        /**
         * The page number of the search hits to display.
         */
        page?: number;
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
    };
    url: '/draft-api/v1/drafts/tag-search';
};

export type GetDraftApiV1DraftsTagSearchErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetDraftApiV1DraftsTagSearchError = GetDraftApiV1DraftsTagSearchErrors[keyof GetDraftApiV1DraftsTagSearchErrors];

export type GetDraftApiV1DraftsTagSearchResponses = {
    200: TagsSearchResultDTO;
};

export type GetDraftApiV1DraftsTagSearchResponse = GetDraftApiV1DraftsTagSearchResponses[keyof GetDraftApiV1DraftsTagSearchResponses];

export type GetDraftApiV1DraftsGrepCodesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return only articles with content matching the specified query.
         */
        query?: string;
        /**
         * The number of search hits to display for each page.
         */
        'page-size'?: number;
        /**
         * The page number of the search hits to display.
         */
        page?: number;
    };
    url: '/draft-api/v1/drafts/grep-codes';
};

export type GetDraftApiV1DraftsGrepCodesErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetDraftApiV1DraftsGrepCodesError = GetDraftApiV1DraftsGrepCodesErrors[keyof GetDraftApiV1DraftsGrepCodesErrors];

export type GetDraftApiV1DraftsGrepCodesResponses = {
    200: GrepCodesSearchResultDTO;
};

export type GetDraftApiV1DraftsGrepCodesResponse = GetDraftApiV1DraftsGrepCodesResponses[keyof GetDraftApiV1DraftsGrepCodesResponses];

export type GetDraftApiV1DraftsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return only articles of specific type(s). To provide multiple types, separate by comma (,).
         */
        articleTypes?: Array<string>;
        /**
         * Return only articles with content matching the specified query.
         */
        query?: string;
        /**
         * Return only articles that have one of the provided ids. To provide multiple ids, separate by comma (,).
         */
        ids?: Array<number>;
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Return only results with provided license. Specifying 'all' gives all results regardless of license.
         */
        license?: string;
        /**
         * The page number of the search hits to display.
         */
        page?: number;
        /**
         * The number of search hits to display for each page.
         */
        'page-size'?: number;
        /**
         * The sorting used on results.
         * The following are supported: relevance, -relevance, title, -title, lastUpdated, -lastUpdated, id, -id.
         * Default is by -relevance (desc) when query is set, and title (asc) when query is empty.
         */
        sort?: string;
        /**
         * A unique string obtained from a search you want to keep scrolling in. To obtain one from a search, provide one of the following values: [0,initial,start,first].
         * When scrolling, the parameters from the initial search is used, except in the case of 'language' and 'fallback'.
         * This value may change between scrolls. Always use the one in the latest scroll result (The context, if unused, dies after 1m).
         * If you are not paginating past 10000 hits, you can ignore this and use 'page' and 'page-size' instead.
         *
         */
        'search-context'?: string;
        /**
         * A comma separated list of codes from GREP API the resources should be filtered by.
         */
        'grep-codes'?: Array<string>;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
    };
    url: '/draft-api/v1/drafts';
};

export type GetDraftApiV1DraftsErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetDraftApiV1DraftsError = GetDraftApiV1DraftsErrors[keyof GetDraftApiV1DraftsErrors];

export type GetDraftApiV1DraftsResponses = {
    200: ArticleSearchResultDTO;
};

export type GetDraftApiV1DraftsResponse = GetDraftApiV1DraftsResponses[keyof GetDraftApiV1DraftsResponses];

export type PostDraftApiV1DraftsData = {
    body: NewArticleDTO;
    path?: never;
    query?: never;
    url: '/draft-api/v1/drafts';
};

export type PostDraftApiV1DraftsErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PostDraftApiV1DraftsError = PostDraftApiV1DraftsErrors[keyof PostDraftApiV1DraftsErrors];

export type PostDraftApiV1DraftsResponses = {
    201: ArticleDTO;
};

export type PostDraftApiV1DraftsResponse = PostDraftApiV1DraftsResponses[keyof PostDraftApiV1DraftsResponses];

export type PostDraftApiV1DraftsSearchData = {
    body: ArticleSearchParamsDTO;
    path?: never;
    query?: never;
    url: '/draft-api/v1/drafts/search';
};

export type PostDraftApiV1DraftsSearchErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PostDraftApiV1DraftsSearchError = PostDraftApiV1DraftsSearchErrors[keyof PostDraftApiV1DraftsSearchErrors];

export type PostDraftApiV1DraftsSearchResponses = {
    200: ArticleSearchResultDTO;
};

export type PostDraftApiV1DraftsSearchResponse = PostDraftApiV1DraftsSearchResponses[keyof PostDraftApiV1DraftsSearchResponses];

export type GetDraftApiV1DraftsStatusStateMachineData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The ID of the article to generate a status state machine for
         */
        articleId?: number;
    };
    url: '/draft-api/v1/drafts/status-state-machine';
};

export type GetDraftApiV1DraftsStatusStateMachineErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetDraftApiV1DraftsStatusStateMachineError = GetDraftApiV1DraftsStatusStateMachineErrors[keyof GetDraftApiV1DraftsStatusStateMachineErrors];

export type GetDraftApiV1DraftsStatusStateMachineResponses = {
    200: Map_List_String;
};

export type GetDraftApiV1DraftsStatusStateMachineResponse = GetDraftApiV1DraftsStatusStateMachineResponses[keyof GetDraftApiV1DraftsStatusStateMachineResponses];

export type GetDraftApiV1DraftsIdsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return only articles that have one of the provided ids. To provide multiple ids, separate by comma (,).
         */
        ids?: Array<number>;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * The number of search hits to display for each page.
         */
        'page-size'?: number;
        /**
         * The page number of the search hits to display.
         */
        page?: number;
    };
    url: '/draft-api/v1/drafts/ids';
};

export type GetDraftApiV1DraftsIdsErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetDraftApiV1DraftsIdsError = GetDraftApiV1DraftsIdsErrors[keyof GetDraftApiV1DraftsIdsErrors];

export type GetDraftApiV1DraftsIdsResponses = {
    200: Array<ArticleDTO>;
};

export type GetDraftApiV1DraftsIdsResponse = GetDraftApiV1DraftsIdsResponses[keyof GetDraftApiV1DraftsIdsResponses];

export type GetDraftApiV1DraftsArticleIdData = {
    body?: never;
    path: {
        /**
         * Id of the article that is to be fetched
         */
        article_id: number;
    };
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
    };
    url: '/draft-api/v1/drafts/{article_id}';
};

export type GetDraftApiV1DraftsArticleIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetDraftApiV1DraftsArticleIdError = GetDraftApiV1DraftsArticleIdErrors[keyof GetDraftApiV1DraftsArticleIdErrors];

export type GetDraftApiV1DraftsArticleIdResponses = {
    200: ArticleDTO;
};

export type GetDraftApiV1DraftsArticleIdResponse = GetDraftApiV1DraftsArticleIdResponses[keyof GetDraftApiV1DraftsArticleIdResponses];

export type PatchDraftApiV1DraftsArticleIdData = {
    body: UpdatedArticleDTO;
    path: {
        /**
         * Id of the article that is to be fetched
         */
        article_id: number;
    };
    query?: never;
    url: '/draft-api/v1/drafts/{article_id}';
};

export type PatchDraftApiV1DraftsArticleIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    409: AllErrors;
    502: AllErrors;
    default: AllErrors;
};

export type PatchDraftApiV1DraftsArticleIdError = PatchDraftApiV1DraftsArticleIdErrors[keyof PatchDraftApiV1DraftsArticleIdErrors];

export type PatchDraftApiV1DraftsArticleIdResponses = {
    200: ArticleDTO;
};

export type PatchDraftApiV1DraftsArticleIdResponse = PatchDraftApiV1DraftsArticleIdResponses[keyof PatchDraftApiV1DraftsArticleIdResponses];

export type GetDraftApiV1DraftsArticleIdHistoryData = {
    body?: never;
    path: {
        /**
         * Id of the article that is to be fetched
         */
        article_id: number;
    };
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
    };
    url: '/draft-api/v1/drafts/{article_id}/history';
};

export type GetDraftApiV1DraftsArticleIdHistoryErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetDraftApiV1DraftsArticleIdHistoryError = GetDraftApiV1DraftsArticleIdHistoryErrors[keyof GetDraftApiV1DraftsArticleIdHistoryErrors];

export type GetDraftApiV1DraftsArticleIdHistoryResponses = {
    200: Array<ArticleDTO>;
};

export type GetDraftApiV1DraftsArticleIdHistoryResponse = GetDraftApiV1DraftsArticleIdHistoryResponses[keyof GetDraftApiV1DraftsArticleIdHistoryResponses];

export type GetDraftApiV1DraftsArticleIdRevisionHistoryData = {
    body?: never;
    path: {
        /**
         * Id of the article that is to be fetched
         */
        article_id: number;
    };
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
    };
    url: '/draft-api/v1/drafts/{article_id}/revision-history';
};

export type GetDraftApiV1DraftsArticleIdRevisionHistoryErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetDraftApiV1DraftsArticleIdRevisionHistoryError = GetDraftApiV1DraftsArticleIdRevisionHistoryErrors[keyof GetDraftApiV1DraftsArticleIdRevisionHistoryErrors];

export type GetDraftApiV1DraftsArticleIdRevisionHistoryResponses = {
    200: ArticleRevisionHistoryDTO;
};

export type GetDraftApiV1DraftsArticleIdRevisionHistoryResponse = GetDraftApiV1DraftsArticleIdRevisionHistoryResponses[keyof GetDraftApiV1DraftsArticleIdRevisionHistoryResponses];

export type GetDraftApiV1DraftsExternalIdDeprecatedNodeIdData = {
    body?: never;
    path: {
        deprecated_node_id: number;
    };
    query?: never;
    url: '/draft-api/v1/drafts/external_id/{deprecated_node_id}';
};

export type GetDraftApiV1DraftsExternalIdDeprecatedNodeIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetDraftApiV1DraftsExternalIdDeprecatedNodeIdError = GetDraftApiV1DraftsExternalIdDeprecatedNodeIdErrors[keyof GetDraftApiV1DraftsExternalIdDeprecatedNodeIdErrors];

export type GetDraftApiV1DraftsExternalIdDeprecatedNodeIdResponses = {
    200: ContentIdDTO;
};

export type GetDraftApiV1DraftsExternalIdDeprecatedNodeIdResponse = GetDraftApiV1DraftsExternalIdDeprecatedNodeIdResponses[keyof GetDraftApiV1DraftsExternalIdDeprecatedNodeIdResponses];

export type PutDraftApiV1DraftsArticleIdStatusStatusData = {
    body?: never;
    path: {
        /**
         * Id of the article that is to be fetched
         */
        article_id: number;
        /**
         * An article status
         */
        STATUS: string;
    };
    query?: never;
    url: '/draft-api/v1/drafts/{article_id}/status/{STATUS}';
};

export type PutDraftApiV1DraftsArticleIdStatusStatusErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PutDraftApiV1DraftsArticleIdStatusStatusError = PutDraftApiV1DraftsArticleIdStatusStatusErrors[keyof PutDraftApiV1DraftsArticleIdStatusStatusErrors];

export type PutDraftApiV1DraftsArticleIdStatusStatusResponses = {
    200: ArticleDTO;
};

export type PutDraftApiV1DraftsArticleIdStatusStatusResponse = PutDraftApiV1DraftsArticleIdStatusStatusResponses[keyof PutDraftApiV1DraftsArticleIdStatusStatusResponses];

export type PutDraftApiV1DraftsArticleIdValidateData = {
    body?: UpdatedArticleDTO;
    path: {
        /**
         * Id of the article that is to be fetched
         */
        article_id: number;
    };
    query?: {
        import_validate?: boolean;
    };
    url: '/draft-api/v1/drafts/{article_id}/validate';
};

export type PutDraftApiV1DraftsArticleIdValidateErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PutDraftApiV1DraftsArticleIdValidateError = PutDraftApiV1DraftsArticleIdValidateErrors[keyof PutDraftApiV1DraftsArticleIdValidateErrors];

export type PutDraftApiV1DraftsArticleIdValidateResponses = {
    200: ContentIdDTO;
};

export type PutDraftApiV1DraftsArticleIdValidateResponse = PutDraftApiV1DraftsArticleIdValidateResponses[keyof PutDraftApiV1DraftsArticleIdValidateResponses];

export type DeleteDraftApiV1DraftsArticleIdLanguageLanguageData = {
    body?: never;
    path: {
        /**
         * Id of the article that is to be fetched
         */
        article_id: number;
        /**
         * The ISO 639-1 language code describing language.
         */
        language: string;
    };
    query?: never;
    url: '/draft-api/v1/drafts/{article_id}/language/{language}';
};

export type DeleteDraftApiV1DraftsArticleIdLanguageLanguageErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type DeleteDraftApiV1DraftsArticleIdLanguageLanguageError = DeleteDraftApiV1DraftsArticleIdLanguageLanguageErrors[keyof DeleteDraftApiV1DraftsArticleIdLanguageLanguageErrors];

export type DeleteDraftApiV1DraftsArticleIdLanguageLanguageResponses = {
    200: ArticleDTO;
};

export type DeleteDraftApiV1DraftsArticleIdLanguageLanguageResponse = DeleteDraftApiV1DraftsArticleIdLanguageLanguageResponses[keyof DeleteDraftApiV1DraftsArticleIdLanguageLanguageResponses];

export type PostDraftApiV1DraftsCloneArticleIdData = {
    body?: never;
    path: {
        /**
         * Id of the article that is to be fetched
         */
        article_id: number;
    };
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
        /**
         * Add a string to the title marking this article as a copy, defaults to 'true'.
         */
        'copied-title-postfix'?: boolean;
    };
    url: '/draft-api/v1/drafts/clone/{article_id}';
};

export type PostDraftApiV1DraftsCloneArticleIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PostDraftApiV1DraftsCloneArticleIdError = PostDraftApiV1DraftsCloneArticleIdErrors[keyof PostDraftApiV1DraftsCloneArticleIdErrors];

export type PostDraftApiV1DraftsCloneArticleIdResponses = {
    200: ArticleDTO;
};

export type PostDraftApiV1DraftsCloneArticleIdResponse = PostDraftApiV1DraftsCloneArticleIdResponses[keyof PostDraftApiV1DraftsCloneArticleIdResponses];

export type PostDraftApiV1DraftsPartialPublishArticleIdData = {
    body: Array<PartialArticleFieldsDTO>;
    path: {
        /**
         * Id of the article that is to be fetched
         */
        article_id: number;
    };
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
    };
    url: '/draft-api/v1/drafts/partial-publish/{article_id}';
};

export type PostDraftApiV1DraftsPartialPublishArticleIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PostDraftApiV1DraftsPartialPublishArticleIdError = PostDraftApiV1DraftsPartialPublishArticleIdErrors[keyof PostDraftApiV1DraftsPartialPublishArticleIdErrors];

export type PostDraftApiV1DraftsPartialPublishArticleIdResponses = {
    200: ArticleDTO;
};

export type PostDraftApiV1DraftsPartialPublishArticleIdResponse = PostDraftApiV1DraftsPartialPublishArticleIdResponses[keyof PostDraftApiV1DraftsPartialPublishArticleIdResponses];

export type PostDraftApiV1DraftsPartialPublishData = {
    body: PartialBulkArticlesDTO;
    path?: never;
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
    };
    url: '/draft-api/v1/drafts/partial-publish';
};

export type PostDraftApiV1DraftsPartialPublishErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PostDraftApiV1DraftsPartialPublishError = PostDraftApiV1DraftsPartialPublishErrors[keyof PostDraftApiV1DraftsPartialPublishErrors];

export type PostDraftApiV1DraftsPartialPublishResponses = {
    200: MultiPartialPublishResultDTO;
};

export type PostDraftApiV1DraftsPartialPublishResponse = PostDraftApiV1DraftsPartialPublishResponses[keyof PostDraftApiV1DraftsPartialPublishResponses];

export type PostDraftApiV1DraftsCopyrevisiondatesNodeIdData = {
    body?: never;
    path: {
        /**
         * Id of the taxonomy node to process
         */
        node_id: string;
    };
    query?: never;
    url: '/draft-api/v1/drafts/copyRevisionDates/{node_id}';
};

export type PostDraftApiV1DraftsCopyrevisiondatesNodeIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PostDraftApiV1DraftsCopyrevisiondatesNodeIdError = PostDraftApiV1DraftsCopyrevisiondatesNodeIdErrors[keyof PostDraftApiV1DraftsCopyrevisiondatesNodeIdErrors];

export type PostDraftApiV1DraftsCopyrevisiondatesNodeIdResponses = {
    204: void;
};

export type PostDraftApiV1DraftsCopyrevisiondatesNodeIdResponse = PostDraftApiV1DraftsCopyrevisiondatesNodeIdResponses[keyof PostDraftApiV1DraftsCopyrevisiondatesNodeIdResponses];

export type GetDraftApiV1DraftsSlugSlugData = {
    body?: never;
    path: {
        /**
         * Slug of the article that is to be fetched.
         */
        slug: string;
    };
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
    };
    url: '/draft-api/v1/drafts/slug/{slug}';
};

export type GetDraftApiV1DraftsSlugSlugErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetDraftApiV1DraftsSlugSlugError = GetDraftApiV1DraftsSlugSlugErrors[keyof GetDraftApiV1DraftsSlugSlugErrors];

export type GetDraftApiV1DraftsSlugSlugResponses = {
    200: ArticleDTO;
};

export type GetDraftApiV1DraftsSlugSlugResponse = GetDraftApiV1DraftsSlugSlugResponses[keyof GetDraftApiV1DraftsSlugSlugResponses];

export type PostDraftApiV1DraftsMigrateGrepsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/draft-api/v1/drafts/migrate-greps';
};

export type PostDraftApiV1DraftsMigrateGrepsErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PostDraftApiV1DraftsMigrateGrepsError = PostDraftApiV1DraftsMigrateGrepsErrors[keyof PostDraftApiV1DraftsMigrateGrepsErrors];

export type PostDraftApiV1DraftsMigrateGrepsResponses = {
    202: unknown;
};

export type PostDraftApiV1DraftsNotesData = {
    body: AddMultipleNotesDTO;
    path?: never;
    query?: never;
    url: '/draft-api/v1/drafts/notes';
};

export type PostDraftApiV1DraftsNotesErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    409: AllErrors;
    default: AllErrors;
};

export type PostDraftApiV1DraftsNotesError = PostDraftApiV1DraftsNotesErrors[keyof PostDraftApiV1DraftsNotesErrors];

export type PostDraftApiV1DraftsNotesResponses = {
    204: void;
};

export type PostDraftApiV1DraftsNotesResponse = PostDraftApiV1DraftsNotesResponses[keyof PostDraftApiV1DraftsNotesResponses];

export type DeleteDraftApiV1DraftsArticleIdCurrentRevisionData = {
    body?: never;
    path: {
        /**
         * Id of the article that is to be fetched
         */
        article_id: number;
    };
    query?: never;
    url: '/draft-api/v1/drafts/{article_id}/current-revision';
};

export type DeleteDraftApiV1DraftsArticleIdCurrentRevisionErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    422: AllErrors;
    default: AllErrors;
};

export type DeleteDraftApiV1DraftsArticleIdCurrentRevisionError = DeleteDraftApiV1DraftsArticleIdCurrentRevisionErrors[keyof DeleteDraftApiV1DraftsArticleIdCurrentRevisionErrors];

export type DeleteDraftApiV1DraftsArticleIdCurrentRevisionResponses = {
    204: void;
};

export type DeleteDraftApiV1DraftsArticleIdCurrentRevisionResponse = DeleteDraftApiV1DraftsArticleIdCurrentRevisionResponses[keyof DeleteDraftApiV1DraftsArticleIdCurrentRevisionResponses];

export type DeleteDraftApiV1FilesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Path to file. Eg: resources/awdW2CaX.png
         */
        path?: string;
    };
    url: '/draft-api/v1/files';
};

export type DeleteDraftApiV1FilesErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type DeleteDraftApiV1FilesError = DeleteDraftApiV1FilesErrors[keyof DeleteDraftApiV1FilesErrors];

export type DeleteDraftApiV1FilesResponses = {
    204: void;
};

export type DeleteDraftApiV1FilesResponse = DeleteDraftApiV1FilesResponses[keyof DeleteDraftApiV1FilesResponses];

export type PostDraftApiV1FilesData = {
    body: FileForm;
    path?: never;
    query?: never;
    url: '/draft-api/v1/files';
};

export type PostDraftApiV1FilesErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PostDraftApiV1FilesError = PostDraftApiV1FilesErrors[keyof PostDraftApiV1FilesErrors];

export type PostDraftApiV1FilesResponses = {
    200: UploadedFileDTO;
};

export type PostDraftApiV1FilesResponse = PostDraftApiV1FilesResponses[keyof PostDraftApiV1FilesResponses];

export type GetDraftApiV1UserDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/draft-api/v1/user-data';
};

export type GetDraftApiV1UserDataErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetDraftApiV1UserDataError = GetDraftApiV1UserDataErrors[keyof GetDraftApiV1UserDataErrors];

export type GetDraftApiV1UserDataResponses = {
    200: UserDataDTO;
};

export type GetDraftApiV1UserDataResponse = GetDraftApiV1UserDataResponses[keyof GetDraftApiV1UserDataResponses];

export type PatchDraftApiV1UserDataData = {
    body: UpdatedUserDataDTO;
    path?: never;
    query?: never;
    url: '/draft-api/v1/user-data';
};

export type PatchDraftApiV1UserDataErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PatchDraftApiV1UserDataError = PatchDraftApiV1UserDataErrors[keyof PatchDraftApiV1UserDataErrors];

export type PatchDraftApiV1UserDataResponses = {
    200: UserDataDTO;
};

export type PatchDraftApiV1UserDataResponse = PatchDraftApiV1UserDataResponses[keyof PatchDraftApiV1UserDataResponses];

export type GetDraftApiV1UserDataResponsiblesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/draft-api/v1/user-data/responsibles';
};

export type GetDraftApiV1UserDataResponsiblesErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetDraftApiV1UserDataResponsiblesError = GetDraftApiV1UserDataResponsiblesErrors[keyof GetDraftApiV1UserDataResponsiblesErrors];

export type GetDraftApiV1UserDataResponsiblesResponses = {
    200: Array<string>;
};

export type GetDraftApiV1UserDataResponsiblesResponse = GetDraftApiV1UserDataResponsiblesResponses[keyof GetDraftApiV1UserDataResponsiblesResponses];

export type GetDraftApiV1UserDataEditorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/draft-api/v1/user-data/editors';
};

export type GetDraftApiV1UserDataEditorsErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetDraftApiV1UserDataEditorsError = GetDraftApiV1UserDataEditorsErrors[keyof GetDraftApiV1UserDataEditorsErrors];

export type GetDraftApiV1UserDataEditorsResponses = {
    200: Array<string>;
};

export type GetDraftApiV1UserDataEditorsResponse = GetDraftApiV1UserDataEditorsResponses[keyof GetDraftApiV1UserDataEditorsResponses];
