/**
 * Copyright (c) 2026-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// @ts-check

import graphqlPlugin from "@graphql-eslint/eslint-plugin";
import tseslint from "typescript-eslint";

// GraphQL is the only thing eslint lints; everything else lives in oxlint.config.ts.

/** Projects whose GraphQL is operations and fragments sent to the schema graphql-api serves. */
const operationProjects = ["ndla-frontend", "editorial-frontend"];

// Schema and document pointers are resolved by graphql-eslint against the working directory, not
// against this file, so they are absolute — each project lints from its own directory.
const root = import.meta.dirname;

/** The schema every operation is validated against, generated by `pnpm run generate-gql`. */
const schema = `${root}/ndla-frontend/src/schema.graphql`;

const config = [
  {
    ignores: [
      "**/graphqlTypes.ts",
      "**/schema.graphql",
      "**/es/**",
      "**/lib/**",
      "**/dist/**",
      "**/build/**",
      "**/public/**",
      "**/e2e/apiMocks/**",
      "**/e2e/fixtures/**",
    ],
  },
  {
    // The processor hands the host file's own source back as its last block, so TS files need a
    // TS parser even though no JS/TS rules are enabled here. Those files still carry
    // `eslint-disable` comments naming oxlint's rules, which eslint would report as unknown, so
    // the lint scripts pass `--no-inline-config` to ignore directives outright.
    files: [...operationProjects, "graphql-api"].map((project) => `${project}/src/**/*.{ts,tsx}`),
    languageOptions: { parser: tseslint.parser },
    processor: graphqlPlugin.processor,
  },
  {
    files: operationProjects.map((project) => `${project}/**/*.graphql`),
    languageOptions: {
      parser: graphqlPlugin.parser,
      parserOptions: {
        graphQLConfig: {
          schema,
          documents: operationProjects.map((project) => `${root}/${project}/src/**/*.{ts,tsx}`),
        },
      },
    },
    plugins: { "@graphql-eslint": graphqlPlugin },
    rules: {
      ...graphqlPlugin.configs["flat/operations-recommended"].rules,
      // Operation and fragment names follow codegen's `Component_Type` convention.
      "@graphql-eslint/naming-convention": "off",
      "@graphql-eslint/selection-set-depth": "off",
      "@graphql-eslint/require-selections": "off",
    },
  },
  {
    // graphql-api defines the schema rather than querying it, so it gets the schema rules.
    files: ["graphql-api/**/*.graphql"],
    languageOptions: {
      parser: graphqlPlugin.parser,
      parserOptions: { graphQLConfig: { schema: `${root}/graphql-api/src/schema.ts` } },
    },
    plugins: { "@graphql-eslint": graphqlPlugin },
    rules: {
      ...graphqlPlugin.configs["flat/schema-recommended"].rules,
      // The schema is a published API: these fire on long-standing types and fields that cannot
      // be renamed or reshaped without breaking clients, so only the structural rules are kept.
      "@graphql-eslint/require-description": "off",
      "@graphql-eslint/strict-id-in-types": "off",
      "@graphql-eslint/no-typename-prefix": "off",
      "@graphql-eslint/naming-convention": "off",
      // TODO: turn back on once the types it reports as unreachable are removed.
      "@graphql-eslint/no-unreachable-types": "off",
    },
  },
];

export default config;
