packages:
  - packages
  - packages/packages/*
  - ndla-frontend
  - editorial-frontend
  - graphql-api
  - api-documentation

catalog:
  "@ark-ui/react": ^5.37.2
  "@pandacss/config": &pandaversion "^1.10.0"
  "@pandacss/core": *pandaversion
  "@pandacss/dev": *pandaversion
  "@pandacss/extractor": *pandaversion
  "@pandacss/generator": *pandaversion
  "@pandacss/is-valid-prop": *pandaversion
  "@pandacss/logger": *pandaversion
  "@pandacss/mcp": *pandaversion
  "@pandacss/node": *pandaversion
  "@pandacss/parser": *pandaversion
  "@pandacss/plugin-lightningcss": *pandaversion
  "@pandacss/plugin-svelte": *pandaversion
  "@pandacss/plugin-vue": *pandaversion
  "@pandacss/postcss": *pandaversion
  "@pandacss/preset-base": *pandaversion
  "@pandacss/preset-panda": *pandaversion
  "@pandacss/reporter": *pandaversion
  "@pandacss/shared": *pandaversion
  "@pandacss/token-dictionary": *pandaversion
  "@pandacss/types": *pandaversion
  "@playwright/test": ^1.60.0
  "@testing-library/dom": ^10.4.1
  "@testing-library/jest-dom": ^6.9.1
  "@testing-library/react": ^16.3.2
  "@types/node": ^24.13.2
  "@types/react": ^19.2.17
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^6.0.3
  eslint: ^9.39.4
  express: ^5.2.1
  graphql: ^16.13.2
  html-react-parser: ^6.0.1
  i18next: ^26.0.3
  jsdom: ^29.1.1
  oxfmt: ^0.57.0
  oxlint: ^1.72.0
  postcss: ^8.5.18
  react-dom: ^19.2.7
  react-i18next: ^17.0.2
  react-router: ^8.0.1
  react: ^19.2.7
  slate-dom: ^0.124.1
  slate-history: ^0.113.1
  slate-react: ^0.124.0
  slate: ^0.124.1
  tsdown: ^0.22.2
  typescript-eslint: ^8.62.1
  typescript: ^6.0.3
  vite: ^8.1.0
  vitest: ^4.1.9

allowBuilds:
  "@apollo/protobufjs": true
  "@scarf/scarf": false
  "@sentry/cli": true
  esbuild: true
  nx: true
  protobufjs: true
