/**
 * Copyright (c) 2026-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import { defineConfig } from "oxlint";
import baseConfig, { sharedIgnorePatterns } from "../packages/packages/oxlint-config/src/index.ts";

export default defineConfig({
  extends: [baseConfig],
  options: {
    typeAware: true,
  },
  ignorePatterns: [
    ...sharedIgnorePatterns,
    // generated by `pnpm run generate-schema-types`
    "src/types/schema.d.ts",
  ],
});
