// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteConceptApiV1DraftsConceptIdData, DeleteConceptApiV1DraftsConceptIdErrors, DeleteConceptApiV1DraftsConceptIdResponses, GetConceptApiV1ConceptsConceptIdData, GetConceptApiV1ConceptsConceptIdErrors, GetConceptApiV1ConceptsConceptIdResponses, GetConceptApiV1ConceptsData, GetConceptApiV1ConceptsErrors, GetConceptApiV1ConceptsResponses, GetConceptApiV1ConceptsTagsData, GetConceptApiV1ConceptsTagsErrors, GetConceptApiV1ConceptsTagsResponses, GetConceptApiV1DraftsConceptIdData, GetConceptApiV1DraftsConceptIdErrors, GetConceptApiV1DraftsConceptIdResponses, GetConceptApiV1DraftsData, GetConceptApiV1DraftsErrors, GetConceptApiV1DraftsResponses, GetConceptApiV1DraftsStatusStateMachineData, GetConceptApiV1DraftsStatusStateMachineErrors, GetConceptApiV1DraftsStatusStateMachineResponses, GetConceptApiV1DraftsTagsData, GetConceptApiV1DraftsTagSearchData, GetConceptApiV1DraftsTagSearchErrors, GetConceptApiV1DraftsTagSearchResponses, GetConceptApiV1DraftsTagsErrors, GetConceptApiV1DraftsTagsResponses, PatchConceptApiV1DraftsConceptIdData, PatchConceptApiV1DraftsConceptIdErrors, PatchConceptApiV1DraftsConceptIdResponses, PostConceptApiV1ConceptsSearchData, PostConceptApiV1ConceptsSearchErrors, PostConceptApiV1ConceptsSearchResponses, PostConceptApiV1DraftsData, PostConceptApiV1DraftsErrors, PostConceptApiV1DraftsResponses, PostConceptApiV1DraftsSearchData, PostConceptApiV1DraftsSearchErrors, PostConceptApiV1DraftsSearchResponses, PutConceptApiV1DraftsConceptIdStatusStatusData, PutConceptApiV1DraftsConceptIdStatusStatusErrors, PutConceptApiV1DraftsConceptIdStatusStatusResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get status state machine
 *
 * Get status state machine
 */
export const getConceptApiV1DraftsStatusStateMachine = <ThrowOnError extends boolean = false>(options?: Options<GetConceptApiV1DraftsStatusStateMachineData, ThrowOnError>): RequestResult<GetConceptApiV1DraftsStatusStateMachineResponses, GetConceptApiV1DraftsStatusStateMachineErrors, ThrowOnError> => (options?.client ?? client).get<GetConceptApiV1DraftsStatusStateMachineResponses, GetConceptApiV1DraftsStatusStateMachineErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/concept-api/v1/drafts/status-state-machine',
    ...options
});

/**
 * Returns a list of all tags in the specified subjects
 *
 * Returns a list of all tags in the specified subjects
 */
export const getConceptApiV1DraftsTags = <ThrowOnError extends boolean = false>(options?: Options<GetConceptApiV1DraftsTagsData, ThrowOnError>): RequestResult<GetConceptApiV1DraftsTagsResponses, GetConceptApiV1DraftsTagsErrors, ThrowOnError> => (options?.client ?? client).get<GetConceptApiV1DraftsTagsResponses, GetConceptApiV1DraftsTagsErrors, ThrowOnError>({ url: '/concept-api/v1/drafts/tags', ...options });

/**
 * Show all concepts
 *
 * Shows all concepts. You can search it too.
 */
export const postConceptApiV1DraftsSearch = <ThrowOnError extends boolean = false>(options: Options<PostConceptApiV1DraftsSearchData, ThrowOnError>): RequestResult<PostConceptApiV1DraftsSearchResponses, PostConceptApiV1DraftsSearchErrors, ThrowOnError> => (options.client ?? client).post<PostConceptApiV1DraftsSearchResponses, PostConceptApiV1DraftsSearchErrors, ThrowOnError>({
    url: '/concept-api/v1/drafts/search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete language from concept
 *
 * Delete language from concept
 */
export const deleteConceptApiV1DraftsConceptId = <ThrowOnError extends boolean = false>(options: Options<DeleteConceptApiV1DraftsConceptIdData, ThrowOnError>): RequestResult<DeleteConceptApiV1DraftsConceptIdResponses, DeleteConceptApiV1DraftsConceptIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteConceptApiV1DraftsConceptIdResponses, DeleteConceptApiV1DraftsConceptIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/concept-api/v1/drafts/{concept_id}',
    ...options
});

/**
 * Show concept with a specified id
 *
 * Shows the concept for the specified id.
 */
export const getConceptApiV1DraftsConceptId = <ThrowOnError extends boolean = false>(options: Options<GetConceptApiV1DraftsConceptIdData, ThrowOnError>): RequestResult<GetConceptApiV1DraftsConceptIdResponses, GetConceptApiV1DraftsConceptIdErrors, ThrowOnError> => (options.client ?? client).get<GetConceptApiV1DraftsConceptIdResponses, GetConceptApiV1DraftsConceptIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/concept-api/v1/drafts/{concept_id}',
    ...options
});

/**
 * Update a concept
 *
 * Update a concept
 */
export const patchConceptApiV1DraftsConceptId = <ThrowOnError extends boolean = false>(options: Options<PatchConceptApiV1DraftsConceptIdData, ThrowOnError>): RequestResult<PatchConceptApiV1DraftsConceptIdResponses, PatchConceptApiV1DraftsConceptIdErrors, ThrowOnError> => (options.client ?? client).patch<PatchConceptApiV1DraftsConceptIdResponses, PatchConceptApiV1DraftsConceptIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/concept-api/v1/drafts/{concept_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update status of a concept
 *
 * Update status of a concept
 */
export const putConceptApiV1DraftsConceptIdStatusStatus = <ThrowOnError extends boolean = false>(options: Options<PutConceptApiV1DraftsConceptIdStatusStatusData, ThrowOnError>): RequestResult<PutConceptApiV1DraftsConceptIdStatusStatusResponses, PutConceptApiV1DraftsConceptIdStatusStatusErrors, ThrowOnError> => (options.client ?? client).put<PutConceptApiV1DraftsConceptIdStatusStatusResponses, PutConceptApiV1DraftsConceptIdStatusStatusErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/concept-api/v1/drafts/{concept_id}/status/{STATUS}',
    ...options
});

/**
 * Retrieves a list of all previously used tags in concepts
 *
 * Retrieves a list of all previously used tags in concepts
 */
export const getConceptApiV1DraftsTagSearch = <ThrowOnError extends boolean = false>(options?: Options<GetConceptApiV1DraftsTagSearchData, ThrowOnError>): RequestResult<GetConceptApiV1DraftsTagSearchResponses, GetConceptApiV1DraftsTagSearchErrors, ThrowOnError> => (options?.client ?? client).get<GetConceptApiV1DraftsTagSearchResponses, GetConceptApiV1DraftsTagSearchErrors, ThrowOnError>({ url: '/concept-api/v1/drafts/tag-search', ...options });

/**
 * Show all concepts
 *
 * Shows all concepts. You can search it too.
 */
export const getConceptApiV1Drafts = <ThrowOnError extends boolean = false>(options?: Options<GetConceptApiV1DraftsData, ThrowOnError>): RequestResult<GetConceptApiV1DraftsResponses, GetConceptApiV1DraftsErrors, ThrowOnError> => (options?.client ?? client).get<GetConceptApiV1DraftsResponses, GetConceptApiV1DraftsErrors, ThrowOnError>({
    querySerializer: { parameters: {
            ids: { array: { explode: false } },
            tags: { array: { explode: false } },
            status: { array: { explode: false } },
            users: { array: { explode: false } },
            'embed-resource': { array: { explode: false } },
            'responsible-ids': { array: { explode: false } },
            'aggregate-paths': { array: { explode: false } }
        } },
    url: '/concept-api/v1/drafts',
    ...options
});

/**
 * Create new concept
 *
 * Create new concept
 */
export const postConceptApiV1Drafts = <ThrowOnError extends boolean = false>(options: Options<PostConceptApiV1DraftsData, ThrowOnError>): RequestResult<PostConceptApiV1DraftsResponses, PostConceptApiV1DraftsErrors, ThrowOnError> => (options.client ?? client).post<PostConceptApiV1DraftsResponses, PostConceptApiV1DraftsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/concept-api/v1/drafts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Returns a list of all tags in the specified subjects
 *
 * Returns a list of all tags in the specified subjects
 */
export const getConceptApiV1ConceptsTags = <ThrowOnError extends boolean = false>(options?: Options<GetConceptApiV1ConceptsTagsData, ThrowOnError>): RequestResult<GetConceptApiV1ConceptsTagsResponses, GetConceptApiV1ConceptsTagsErrors, ThrowOnError> => (options?.client ?? client).get<GetConceptApiV1ConceptsTagsResponses, GetConceptApiV1ConceptsTagsErrors, ThrowOnError>({ url: '/concept-api/v1/concepts/tags', ...options });

/**
 * Show concept with a specified id
 *
 * Shows the concept for the specified id.
 */
export const getConceptApiV1ConceptsConceptId = <ThrowOnError extends boolean = false>(options: Options<GetConceptApiV1ConceptsConceptIdData, ThrowOnError>): RequestResult<GetConceptApiV1ConceptsConceptIdResponses, GetConceptApiV1ConceptsConceptIdErrors, ThrowOnError> => (options.client ?? client).get<GetConceptApiV1ConceptsConceptIdResponses, GetConceptApiV1ConceptsConceptIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/concept-api/v1/concepts/{concept_id}',
    ...options
});

/**
 * Show all concepts
 *
 * Shows all concepts. You can search it too.
 */
export const getConceptApiV1Concepts = <ThrowOnError extends boolean = false>(options?: Options<GetConceptApiV1ConceptsData, ThrowOnError>): RequestResult<GetConceptApiV1ConceptsResponses, GetConceptApiV1ConceptsErrors, ThrowOnError> => (options?.client ?? client).get<GetConceptApiV1ConceptsResponses, GetConceptApiV1ConceptsErrors, ThrowOnError>({
    querySerializer: { parameters: {
            ids: { array: { explode: false } },
            tags: { array: { explode: false } },
            'embed-resource': { array: { explode: false } },
            'aggregate-paths': { array: { explode: false } }
        } },
    url: '/concept-api/v1/concepts',
    ...options
});

/**
 * Show all concepts
 *
 * Shows all concepts. You can search it too.
 */
export const postConceptApiV1ConceptsSearch = <ThrowOnError extends boolean = false>(options: Options<PostConceptApiV1ConceptsSearchData, ThrowOnError>): RequestResult<PostConceptApiV1ConceptsSearchResponses, PostConceptApiV1ConceptsSearchErrors, ThrowOnError> => (options.client ?? client).post<PostConceptApiV1ConceptsSearchResponses, PostConceptApiV1ConceptsSearchErrors, ThrowOnError>({
    url: '/concept-api/v1/concepts/search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
