// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AllErrors
 */
export type AllErrors = ErrorBody | NotFoundWithSupportedLanguages | ValidationErrorBody;

/**
 * AuthorDTO
 *
 * Information about an author
 */
export type AuthorDTO = {
    type: ContributorType;
    /**
     * The name of the of the author
     */
    name: string;
};

/**
 * ConceptContent
 */
export type ConceptContent = {
    /**
     * The content of this concept
     */
    content: string;
    /**
     * The html content of this concept
     */
    htmlContent: string;
    /**
     * The language of this concept
     */
    language: string;
};

/**
 * ConceptDTO
 *
 * Information about the concept
 */
export type ConceptDTO = {
    /**
     * The unique id of the concept
     */
    id: number;
    /**
     * The revision of the concept
     */
    revision: number;
    title: ConceptTitleDTO;
    /**
     * The content of the concept
     */
    content?: ConceptContent;
    /**
     * Describes the copyright information for the concept
     */
    copyright?: DraftCopyrightDTO;
    /**
     * URL for the source of the concept
     */
    source?: string;
    tags?: ConceptTagsDTO;
    /**
     * When the concept was created
     */
    created: string;
    /**
     * When the concept was last updated
     */
    updated: string;
    /**
     * List of people that updated this concept
     */
    updatedBy?: Array<string>;
    /**
     * All available languages of the current concept
     */
    supportedLanguages: Array<string>;
    /**
     * Status information of the concept
     */
    status: StatusDTO;
    visualElement?: VisualElementDTO;
    responsible?: ResponsibleDTO;
    /**
     * Type of concept. 'concept', or 'gloss'
     */
    conceptType: string;
    glossData?: GlossDataDTO;
    /**
     * Describes the changes made to the concept, only visible to editors
     */
    editorNotes?: Array<EditorNoteDTO>;
};

/**
 * ConceptSearchParamsDTO
 *
 * The search parameters
 */
export type ConceptSearchParamsDTO = {
    /**
     * The search query.
     */
    query?: string;
    /**
     * The ISO 639-1 language code describing language used in query-params.
     */
    language?: string;
    /**
     * The page number of the search hits to display.
     */
    page?: number;
    /**
     * The number of search hits to display for each page.
     */
    pageSize?: number;
    /**
     * Return only articles that have one of the provided ids.
     */
    ids?: Array<number>;
    sort?: Sort;
    /**
     * Whether to fallback to existing language if not found in selected language.
     */
    fallback?: boolean;
    /**
     * A search context retrieved from the response header of a previous search.
     */
    scrollId?: string;
    /**
     * A comma-separated list of tags to filter the search by.
     */
    tags?: Array<string>;
    /**
     * If provided, only return concept where query matches title exactly.
     */
    exactMatch?: boolean;
    /**
     * Embed resource type that should exist in the concepts.
     */
    embedResource?: Array<string>;
    /**
     * Embed id attribute that should exist in the concepts.
     */
    embedId?: string;
    /**
     * The type of concepts to return.
     */
    conceptType?: string;
    /**
     * A list of index paths to aggregate over
     */
    aggregatePaths?: Array<string>;
};

/**
 * ConceptSearchResultDTO
 *
 * Information about search-results
 */
export type ConceptSearchResultDTO = {
    /**
     * The total number of articles matching this query
     */
    totalCount: number;
    /**
     * For which page results are shown from
     */
    page?: number;
    /**
     * The number of results per page
     */
    pageSize: number;
    /**
     * The chosen search language
     */
    language: string;
    /**
     * The search results
     */
    results: Array<ConceptSummaryDTO>;
    /**
     * The aggregated fields if specified in query
     */
    aggregations: Array<MultiSearchTermsAggregationDTO>;
};

/**
 * ConceptSummaryDTO
 *
 * Information about the concept
 */
export type ConceptSummaryDTO = {
    /**
     * The unique id of the concept
     */
    id: number;
    title: ConceptTitleDTO;
    /**
     * The content of the concept in available languages
     */
    content: ConceptContent;
    tags?: ConceptTagsDTO;
    /**
     * All available languages of the current concept
     */
    supportedLanguages: Array<string>;
    /**
     * The time when the article was last updated
     */
    lastUpdated: string;
    /**
     * When the concept was created
     */
    created: string;
    /**
     * Status information of the concept
     */
    status: StatusDTO;
    /**
     * List of people that edited the concept
     */
    updatedBy: Array<string>;
    /**
     * Describes the license of the concept
     */
    license?: string;
    /**
     * Describes the copyright of the concept
     */
    copyright?: DraftCopyrightDTO;
    visualElement?: VisualElementDTO;
    /**
     * URL for the source of the concept
     */
    source?: string;
    responsible?: ResponsibleDTO;
    /**
     * Type of concept. 'concept', or 'gloss'
     */
    conceptType: string;
    glossData?: GlossDataDTO;
    /**
     * A translated name of the concept type
     */
    conceptTypeName: string;
};

/**
 * ConceptTagsDTO
 *
 * Search tags the concept is tagged with
 */
export type ConceptTagsDTO = {
    /**
     * Searchable tags
     */
    tags: Array<string>;
    /**
     * The ISO 639-1 language code describing which concept translation these tags belongs to
     */
    language: string;
};

/**
 * ConceptTitleDTO
 *
 * Available titles for the concept
 */
export type ConceptTitleDTO = {
    /**
     * The freetext title of this concept
     */
    title: string;
    /**
     * The freetext html title of this concept
     */
    htmlTitle: string;
    /**
     * ISO 639-1 code that represents the language used in the title
     */
    language: string;
};

/**
 * ContributorType
 *
 * The description of the author. Eg. Photographer or Supplier
 */
export type ContributorType = 'artist' | 'cowriter' | 'compiler' | 'composer' | 'correction' | 'director' | 'distributor' | 'editorial' | 'facilitator' | 'idea' | 'illustrator' | 'linguistic' | 'originator' | 'photographer' | 'processor' | 'publisher' | 'reader' | 'rightsholder' | 'scriptwriter' | 'supplier' | 'translator' | 'writer';

/**
 * DraftConceptSearchParamsDTO
 *
 * The search parameters
 */
export type DraftConceptSearchParamsDTO = {
    /**
     * The search query.
     */
    query?: string;
    /**
     * The ISO 639-1 language code describing language used in query-params.
     */
    language?: string;
    /**
     * The page number of the search hits to display.
     */
    page?: number;
    /**
     * The number of search hits to display for each page.
     */
    pageSize?: number;
    /**
     * Return only articles that have one of the provided ids.
     */
    ids?: Array<number>;
    sort?: Sort;
    /**
     * Whether to fallback to existing language if not found in selected language.
     */
    fallback?: boolean;
    /**
     * A search context retrieved from the response header of a previous search.
     */
    scrollId?: string;
    /**
     * A comma-separated list of tags to filter the search by.
     */
    tags?: Array<string>;
    /**
     * A comma-separated list of statuses that should appear in the search.
     */
    status?: Array<string>;
    /**
     * A comma-separated list of users to filter the search by.
     */
    users?: Array<string>;
    /**
     * Embed resource type that should exist in the concepts.
     */
    embedResource?: Array<string>;
    /**
     * Embed id attribute that should exist in the concepts.
     */
    embedId?: string;
    /**
     * A comma-separated list of NDLA IDs to filter the search by.
     */
    responsibleIds?: Array<string>;
    /**
     * The type of concepts to return.
     */
    conceptType?: string;
    /**
     * A list of index paths to aggregate over
     */
    aggregatePaths?: Array<string>;
};

/**
 * DraftCopyrightDTO
 */
export type DraftCopyrightDTO = {
    license?: LicenseDTO;
    /**
     * Reference to where the article is procured
     */
    origin?: string;
    /**
     * List of creators
     */
    creators: Array<AuthorDTO>;
    /**
     * List of processors
     */
    processors: Array<AuthorDTO>;
    /**
     * List of rightsholders
     */
    rightsholders: Array<AuthorDTO>;
    /**
     * Date from which the copyright is valid
     */
    validFrom?: string;
    /**
     * Date to which the copyright is valid
     */
    validTo?: string;
    /**
     * Whether or not the content has been processed
     */
    processed: boolean;
};

/**
 * EditorNoteDTO
 *
 * Information about the editorial notes
 */
export type EditorNoteDTO = {
    /**
     * Editorial note
     */
    note: string;
    /**
     * User which saved the note
     */
    updatedBy: string;
    /**
     * Status of concept at saved time
     */
    status: StatusDTO;
    /**
     * Timestamp of when note was saved
     */
    timestamp: string;
};

/**
 * ErrorBody
 *
 * Information about an error
 */
export type ErrorBody = {
    /**
     * Code stating the type of error
     */
    code: string;
    /**
     * Description of the error
     */
    description: string;
    /**
     * When the error occurred
     */
    occurredAt: string;
    /**
     * Numeric http status code
     */
    statusCode: number;
};

/**
 * GlossDataDTO
 *
 * Information about the gloss
 */
export type GlossDataDTO = {
    /**
     * The gloss itself
     */
    gloss: string;
    /**
     * Word class / part of speech, ex. noun, adjective, verb, adverb, ...
     */
    wordClass: Array<string>;
    /**
     * Original language of the gloss
     */
    originalLanguage: string;
    /**
     * Alternative writing of the gloss
     */
    transcriptions: Map_String;
    /**
     * List of examples of how the gloss can be used
     */
    examples: Array<Array<GlossExampleDTO>>;
};

/**
 * GlossExampleDTO
 *
 * Information about the gloss example
 */
export type GlossExampleDTO = {
    /**
     * Example use of the gloss
     */
    example: string;
    /**
     * Language of the example
     */
    language: string;
    /**
     * Alternative writing of the example
     */
    transcriptions: Map_String;
};

/**
 * LicenseDTO
 *
 * Describes the license of the article
 */
export type LicenseDTO = {
    /**
     * The name of the license
     */
    license: string;
    /**
     * Description of the license
     */
    description?: string;
    /**
     * Url to where the license can be found
     */
    url?: string;
};

/**
 * Map_List_String
 */
export type Map_List_String = {
    [key: string]: Array<string>;
};

/**
 * Map_String
 */
export type Map_String = {
    [key: string]: string;
};

/**
 * MultiSearchTermsAggregationDTO
 *
 * Information about search aggregation on `field`
 */
export type MultiSearchTermsAggregationDTO = {
    /**
     * The field the specific aggregation is matching
     */
    field: string;
    /**
     * Number of documents with values that didn't appear in the aggregation. (Will only happen if there are more than 50 different values)
     */
    sumOtherDocCount: number;
    /**
     * The result is approximate, this gives an approximation of potential errors. (Specifics here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-approximate-counts)
     */
    docCountErrorUpperBound: number;
    /**
     * Values appearing in the field
     */
    values: Array<TermValueDTO>;
};

/**
 * NewConceptDTO
 *
 * Information about the concept
 */
export type NewConceptDTO = {
    /**
     * The language of this concept
     */
    language: string;
    /**
     * Available titles for the concept
     */
    title: string;
    /**
     * The content of the concept
     */
    content?: string;
    /**
     * Describes the copyright information for the concept
     */
    copyright?: DraftCopyrightDTO;
    /**
     * A list of searchable tags
     */
    tags?: Array<string>;
    /**
     * A visual element for the concept. May be anything from an image to a video or H5P
     */
    visualElement?: string;
    /**
     * NDLA ID representing the editor responsible for this article
     */
    responsibleId?: string;
    /**
     * Type of concept. 'concept', or 'gloss'
     */
    conceptType: string;
    glossData?: GlossDataDTO;
};

/**
 * NotFoundWithSupportedLanguages
 *
 * Information about an error
 */
export type NotFoundWithSupportedLanguages = {
    /**
     * Code stating the type of error
     */
    code: string;
    /**
     * Description of the error
     */
    description: string;
    /**
     * When the error occurred
     */
    occurredAt: string;
    /**
     * List of supported languages
     */
    supportedLanguages?: Array<string>;
    /**
     * Numeric http status code
     */
    statusCode: number;
};

/**
 * ResponsibleDTO
 *
 * Object with data representing the editor responsible for this concept
 */
export type ResponsibleDTO = {
    /**
     * NDLA ID of responsible editor
     */
    responsibleId: string;
    /**
     * Date of when the responsible editor was last updated
     */
    lastUpdated: string;
};

/**
 * Sort
 *
 * The sorting used on results. Default is by -relevance.
 */
export type Sort = '-relevance' | 'relevance' | '-title' | 'title' | '-lastUpdated' | 'lastUpdated' | '-id' | 'id' | '-responsibleLastUpdated' | 'responsibleLastUpdated' | 'status' | '-status' | 'subject' | '-subject' | 'conceptType' | '-conceptType';

/**
 * StatusDTO
 */
export type StatusDTO = {
    /**
     * The current status of the concept
     */
    current: string;
    /**
     * Previous statuses this concept has been in
     */
    other: Array<string>;
};

/**
 * TagsSearchResultDTO
 *
 * Information about tags-search-results
 */
export type TagsSearchResultDTO = {
    /**
     * The total number of tags matching this query
     */
    totalCount: number;
    /**
     * For which page results are shown from
     */
    page: number;
    /**
     * The number of results per page
     */
    pageSize: number;
    /**
     * The chosen search language
     */
    language: string;
    /**
     * The search results
     */
    results: Array<string>;
};

/**
 * TermValueDTO
 *
 * Value that appears in the search aggregation
 */
export type TermValueDTO = {
    /**
     * Value that appeared in result
     */
    value: string;
    /**
     * Number of times the value appeared in result
     */
    count: number;
};

/**
 * UpdatedConceptDTO
 *
 * Information about the concept
 */
export type UpdatedConceptDTO = {
    /**
     * The language of this concept
     */
    language: string;
    /**
     * Available titles for the concept
     */
    title?: string;
    /**
     * The content of the concept
     */
    content?: string;
    /**
     * Describes the copyright information for the concept
     */
    copyright?: DraftCopyrightDTO;
    /**
     * A list of searchable tags
     */
    tags?: Array<string>;
    /**
     * The new status of the concept
     */
    status?: string;
    /**
     * A visual element for the concept. May be anything from an image to a video or H5P
     */
    visualElement?: string;
    /**
     * NDLA ID representing the editor responsible for this article
     */
    responsibleId?: string | null;
    /**
     * Type of concept. 'concept', or 'gloss'
     */
    conceptType?: string;
    glossData?: GlossDataDTO;
};

/**
 * ValidationErrorBody
 *
 * Information about an error
 */
export type ValidationErrorBody = {
    /**
     * Code stating the type of error
     */
    code: string;
    /**
     * Description of the error
     */
    description: string;
    /**
     * When the error occurred
     */
    occurredAt: string;
    /**
     * List of validation messages
     */
    messages?: Array<ValidationMessage>;
    /**
     * Numeric http status code
     */
    statusCode: number;
};

/**
 * ValidationMessage
 *
 * A message describing a validation error on a specific field
 */
export type ValidationMessage = {
    /**
     * The field the error occured in
     */
    field: string;
    /**
     * The validation message
     */
    message: string;
};

/**
 * VisualElementDTO
 *
 * A visual element for the concept
 */
export type VisualElementDTO = {
    /**
     * Html containing the visual element. May contain any legal html element, including the embed-tag
     */
    visualElement: string;
    /**
     * The ISO 639-1 language code describing which article translation this visual element belongs to
     */
    language: string;
};

export type GetConceptApiV1DraftsStatusStateMachineData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/concept-api/v1/drafts/status-state-machine';
};

export type GetConceptApiV1DraftsStatusStateMachineErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetConceptApiV1DraftsStatusStateMachineError = GetConceptApiV1DraftsStatusStateMachineErrors[keyof GetConceptApiV1DraftsStatusStateMachineErrors];

export type GetConceptApiV1DraftsStatusStateMachineResponses = {
    200: Map_List_String;
};

export type GetConceptApiV1DraftsStatusStateMachineResponse = GetConceptApiV1DraftsStatusStateMachineResponses[keyof GetConceptApiV1DraftsStatusStateMachineResponses];

export type GetConceptApiV1DraftsTagsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
    };
    url: '/concept-api/v1/drafts/tags';
};

export type GetConceptApiV1DraftsTagsErrors = {
    400: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetConceptApiV1DraftsTagsError = GetConceptApiV1DraftsTagsErrors[keyof GetConceptApiV1DraftsTagsErrors];

export type GetConceptApiV1DraftsTagsResponses = {
    200: Array<string>;
};

export type GetConceptApiV1DraftsTagsResponse = GetConceptApiV1DraftsTagsResponses[keyof GetConceptApiV1DraftsTagsResponses];

export type PostConceptApiV1DraftsSearchData = {
    body: DraftConceptSearchParamsDTO;
    path?: never;
    query?: never;
    url: '/concept-api/v1/drafts/search';
};

export type PostConceptApiV1DraftsSearchErrors = {
    400: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PostConceptApiV1DraftsSearchError = PostConceptApiV1DraftsSearchErrors[keyof PostConceptApiV1DraftsSearchErrors];

export type PostConceptApiV1DraftsSearchResponses = {
    200: ConceptSearchResultDTO;
};

export type PostConceptApiV1DraftsSearchResponse = PostConceptApiV1DraftsSearchResponses[keyof PostConceptApiV1DraftsSearchResponses];

export type DeleteConceptApiV1DraftsConceptIdData = {
    body?: never;
    path: {
        /**
         * Id of the concept that is to be returned
         */
        concept_id: number;
    };
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
    };
    url: '/concept-api/v1/drafts/{concept_id}';
};

export type DeleteConceptApiV1DraftsConceptIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type DeleteConceptApiV1DraftsConceptIdError = DeleteConceptApiV1DraftsConceptIdErrors[keyof DeleteConceptApiV1DraftsConceptIdErrors];

export type DeleteConceptApiV1DraftsConceptIdResponses = {
    200: ConceptDTO;
};

export type DeleteConceptApiV1DraftsConceptIdResponse = DeleteConceptApiV1DraftsConceptIdResponses[keyof DeleteConceptApiV1DraftsConceptIdResponses];

export type GetConceptApiV1DraftsConceptIdData = {
    body?: never;
    path: {
        /**
         * Id of the concept that is to be returned
         */
        concept_id: number;
    };
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
    };
    url: '/concept-api/v1/drafts/{concept_id}';
};

export type GetConceptApiV1DraftsConceptIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetConceptApiV1DraftsConceptIdError = GetConceptApiV1DraftsConceptIdErrors[keyof GetConceptApiV1DraftsConceptIdErrors];

export type GetConceptApiV1DraftsConceptIdResponses = {
    200: ConceptDTO;
};

export type GetConceptApiV1DraftsConceptIdResponse = GetConceptApiV1DraftsConceptIdResponses[keyof GetConceptApiV1DraftsConceptIdResponses];

export type PatchConceptApiV1DraftsConceptIdData = {
    body: UpdatedConceptDTO;
    path: {
        /**
         * Id of the concept that is to be returned
         */
        concept_id: number;
    };
    query?: never;
    url: '/concept-api/v1/drafts/{concept_id}';
};

export type PatchConceptApiV1DraftsConceptIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PatchConceptApiV1DraftsConceptIdError = PatchConceptApiV1DraftsConceptIdErrors[keyof PatchConceptApiV1DraftsConceptIdErrors];

export type PatchConceptApiV1DraftsConceptIdResponses = {
    200: ConceptDTO;
};

export type PatchConceptApiV1DraftsConceptIdResponse = PatchConceptApiV1DraftsConceptIdResponses[keyof PatchConceptApiV1DraftsConceptIdResponses];

export type PutConceptApiV1DraftsConceptIdStatusStatusData = {
    body?: never;
    path: {
        /**
         * Id of the concept that is to be returned
         */
        concept_id: number;
        /**
         * Concept status
         */
        STATUS: string;
    };
    query?: never;
    url: '/concept-api/v1/drafts/{concept_id}/status/{STATUS}';
};

export type PutConceptApiV1DraftsConceptIdStatusStatusErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PutConceptApiV1DraftsConceptIdStatusStatusError = PutConceptApiV1DraftsConceptIdStatusStatusErrors[keyof PutConceptApiV1DraftsConceptIdStatusStatusErrors];

export type PutConceptApiV1DraftsConceptIdStatusStatusResponses = {
    200: ConceptDTO;
};

export type PutConceptApiV1DraftsConceptIdStatusStatusResponse = PutConceptApiV1DraftsConceptIdStatusStatusResponses[keyof PutConceptApiV1DraftsConceptIdStatusStatusResponses];

export type GetConceptApiV1DraftsTagSearchData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return only concepts with content matching the specified query.
         */
        query?: string;
        /**
         * The number of search hits to display for each page.
         */
        'page-size'?: number;
        /**
         * The page number of the search hits to display.
         */
        page?: number;
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
    };
    url: '/concept-api/v1/drafts/tag-search';
};

export type GetConceptApiV1DraftsTagSearchErrors = {
    400: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetConceptApiV1DraftsTagSearchError = GetConceptApiV1DraftsTagSearchErrors[keyof GetConceptApiV1DraftsTagSearchErrors];

export type GetConceptApiV1DraftsTagSearchResponses = {
    200: TagsSearchResultDTO;
};

export type GetConceptApiV1DraftsTagSearchResponse = GetConceptApiV1DraftsTagSearchResponses[keyof GetConceptApiV1DraftsTagSearchResponses];

export type GetConceptApiV1DraftsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return only concepts with content matching the specified query.
         */
        query?: string;
        /**
         * Return only concepts that have one of the provided ids. To provide multiple ids, separate by comma (,).
         */
        ids?: Array<number>;
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * The page number of the search hits to display.
         */
        page?: number;
        /**
         * The number of search hits to display for each page.
         */
        'page-size'?: number;
        /**
         * The sorting used on results.
         * The following are supported: ByRelevanceDesc,ByRelevanceAsc,ByTitleDesc,ByTitleAsc,ByLastUpdatedDesc,ByLastUpdatedAsc,ByIdDesc,ByIdAsc,ByResponsibleLastUpdatedDesc,ByResponsibleLastUpdatedAsc,ByStatusAsc,ByStatusDesc,BySubjectAsc,BySubjectDesc,ByConceptTypeAsc,ByConceptTypeDesc
         * Default is by -relevance (desc) when query is set, and title (asc) when query is empty.
         */
        sort?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
        /**
         * A unique string obtained from a search you want to keep scrolling in. To obtain one from a search, provide one of the following values: [0,initial,start,first].
         * When scrolling, the parameters from the initial search is used, except in the case of 'language' and 'fallback'.
         * This value may change between scrolls. Always use the one in the latest scroll result.
         * If you are not paginating very far, you can ignore this and use 'page' and 'page-size' instead.
         *
         */
        'search-context'?: string;
        /**
         * A comma-separated list of tags to filter the search by.
         */
        tags?: Array<string>;
        /**
         * List of statuses to filter by.
         * A draft only needs to have one of the available statuses to appear in result (OR).
         *
         */
        status?: Array<string>;
        /**
         * List of users to filter by.
         * The value to search for is the user-id from Auth0.
         */
        users?: Array<string>;
        /**
         * Return concepts with matching embed type.
         */
        'embed-resource'?: Array<string>;
        /**
         * Return concepts with matching embed id.
         */
        'embed-id'?: string;
        /**
         * List of responsible ids to filter by (OR filter)
         */
        'responsible-ids'?: Array<string>;
        /**
         * Return only concepts of given type. Allowed values are concept,gloss
         */
        'concept-type'?: string;
        /**
         * List of index-paths that should be term-aggregated and returned in result.
         */
        'aggregate-paths'?: Array<string>;
    };
    url: '/concept-api/v1/drafts';
};

export type GetConceptApiV1DraftsErrors = {
    400: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetConceptApiV1DraftsError = GetConceptApiV1DraftsErrors[keyof GetConceptApiV1DraftsErrors];

export type GetConceptApiV1DraftsResponses = {
    200: ConceptSearchResultDTO;
};

export type GetConceptApiV1DraftsResponse = GetConceptApiV1DraftsResponses[keyof GetConceptApiV1DraftsResponses];

export type PostConceptApiV1DraftsData = {
    body: NewConceptDTO;
    path?: never;
    query?: never;
    url: '/concept-api/v1/drafts';
};

export type PostConceptApiV1DraftsErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PostConceptApiV1DraftsError = PostConceptApiV1DraftsErrors[keyof PostConceptApiV1DraftsErrors];

export type PostConceptApiV1DraftsResponses = {
    201: ConceptDTO;
};

export type PostConceptApiV1DraftsResponse = PostConceptApiV1DraftsResponses[keyof PostConceptApiV1DraftsResponses];

export type GetConceptApiV1ConceptsTagsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
    };
    url: '/concept-api/v1/concepts/tags';
};

export type GetConceptApiV1ConceptsTagsErrors = {
    400: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetConceptApiV1ConceptsTagsError = GetConceptApiV1ConceptsTagsErrors[keyof GetConceptApiV1ConceptsTagsErrors];

export type GetConceptApiV1ConceptsTagsResponses = {
    200: Array<string>;
};

export type GetConceptApiV1ConceptsTagsResponse = GetConceptApiV1ConceptsTagsResponses[keyof GetConceptApiV1ConceptsTagsResponses];

export type GetConceptApiV1ConceptsConceptIdData = {
    body?: never;
    path: {
        /**
         * Id of the concept that is to be returned
         */
        concept_id: number;
    };
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
    };
    url: '/concept-api/v1/concepts/{concept_id}';
};

export type GetConceptApiV1ConceptsConceptIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetConceptApiV1ConceptsConceptIdError = GetConceptApiV1ConceptsConceptIdErrors[keyof GetConceptApiV1ConceptsConceptIdErrors];

export type GetConceptApiV1ConceptsConceptIdResponses = {
    200: ConceptDTO;
};

export type GetConceptApiV1ConceptsConceptIdResponse = GetConceptApiV1ConceptsConceptIdResponses[keyof GetConceptApiV1ConceptsConceptIdResponses];

export type GetConceptApiV1ConceptsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return only concepts with content matching the specified query.
         */
        query?: string;
        /**
         * Return only concepts that have one of the provided ids. To provide multiple ids, separate by comma (,).
         */
        ids?: Array<number>;
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * The page number of the search hits to display.
         */
        page?: number;
        /**
         * The number of search hits to display for each page.
         */
        'page-size'?: number;
        /**
         * The sorting used on results.
         * The following are supported: ByRelevanceDesc,ByRelevanceAsc,ByTitleDesc,ByTitleAsc,ByLastUpdatedDesc,ByLastUpdatedAsc,ByIdDesc,ByIdAsc,ByResponsibleLastUpdatedDesc,ByResponsibleLastUpdatedAsc,ByStatusAsc,ByStatusDesc,BySubjectAsc,BySubjectDesc,ByConceptTypeAsc,ByConceptTypeDesc
         * Default is by -relevance (desc) when query is set, and title (asc) when query is empty.
         */
        sort?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
        /**
         * A unique string obtained from a search you want to keep scrolling in. To obtain one from a search, provide one of the following values: [0,initial,start,first].
         * When scrolling, the parameters from the initial search is used, except in the case of 'language' and 'fallback'.
         * This value may change between scrolls. Always use the one in the latest scroll result.
         * If you are not paginating very far, you can ignore this and use 'page' and 'page-size' instead.
         *
         */
        'search-context'?: string;
        /**
         * A comma-separated list of tags to filter the search by.
         */
        tags?: Array<string>;
        /**
         * If provided, only return concept where query matches title exactly.
         */
        'exact-match'?: boolean;
        /**
         * Return concepts with matching embed type.
         */
        'embed-resource'?: Array<string>;
        /**
         * Return concepts with matching embed id.
         */
        'embed-id'?: string;
        /**
         * Return only concepts of given type. Allowed values are concept,gloss
         */
        'concept-type'?: string;
        /**
         * List of index-paths that should be term-aggregated and returned in result.
         */
        'aggregate-paths'?: Array<string>;
    };
    url: '/concept-api/v1/concepts';
};

export type GetConceptApiV1ConceptsErrors = {
    400: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetConceptApiV1ConceptsError = GetConceptApiV1ConceptsErrors[keyof GetConceptApiV1ConceptsErrors];

export type GetConceptApiV1ConceptsResponses = {
    200: ConceptSearchResultDTO;
};

export type GetConceptApiV1ConceptsResponse = GetConceptApiV1ConceptsResponses[keyof GetConceptApiV1ConceptsResponses];

export type PostConceptApiV1ConceptsSearchData = {
    body: ConceptSearchParamsDTO;
    path?: never;
    query?: never;
    url: '/concept-api/v1/concepts/search';
};

export type PostConceptApiV1ConceptsSearchErrors = {
    400: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PostConceptApiV1ConceptsSearchError = PostConceptApiV1ConceptsSearchErrors[keyof PostConceptApiV1ConceptsSearchErrors];

export type PostConceptApiV1ConceptsSearchResponses = {
    200: ConceptSearchResultDTO;
};

export type PostConceptApiV1ConceptsSearchResponse = PostConceptApiV1ConceptsSearchResponses[keyof PostConceptApiV1ConceptsSearchResponses];
