ALTER TABLE folders
ADD COLUMN created TIMESTAMP DEFAULT NOW() NOT NULL,
ADD COLUMN updated TIMESTAMP DEFAULT NOW() NOT NULL,
ADD COLUMN shared TIMESTAMP DEFAULT NULL;

UPDATE folders SET shared = NOW() WHERE "folders".status = 'shared';