// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AllErrors
 */
export type AllErrors = ErrorBody | NotFoundWithSupportedLanguages | ValidationErrorBody;

/**
 * ArticleContentV2DTO
 *
 * The content of the article in available languages
 */
export type ArticleContentV2DTO = {
    /**
     * The html content
     */
    content: string;
    /**
     * ISO 639-1 code that represents the language used in the content
     */
    language: string;
};

/**
 * ArticleIdV2DTO
 *
 * Id for a single Article
 */
export type ArticleIdV2DTO = {
    /**
     * The unique id of the article
     */
    id: number;
};

/**
 * ArticleIdsDTO
 */
export type ArticleIdsDTO = {
    articleId: number;
    externalIds: Array<string>;
};

/**
 * ArticleIntroductionDTO
 *
 * An introduction for the article
 */
export type ArticleIntroductionDTO = {
    /**
     * The introduction content
     */
    introduction: string;
    /**
     * The html-version introduction content
     */
    htmlIntroduction: string;
    /**
     * The ISO 639-1 language code describing which article translation this introduction belongs to
     */
    language: string;
};

/**
 * ArticleMetaDescriptionDTO
 */
export type ArticleMetaDescriptionDTO = {
    /**
     * The meta description
     */
    metaDescription: string;
    /**
     * The ISO 639-1 language code describing which article translation this meta description belongs to
     */
    language: string;
};

/**
 * ArticleMetaImageDTO
 *
 * A meta image for the article
 */
export type ArticleMetaImageDTO = {
    /**
     * The meta image url
     */
    url: string;
    /**
     * The alt text for the meta image
     */
    alt: string;
    /**
     * The ISO 639-1 language code describing which article translation this meta description belongs to
     */
    language: string;
};

/**
 * ArticleRevisionHistoryDTO
 *
 * Information about article revision history
 */
export type ArticleRevisionHistoryDTO = {
    /**
     * The revisions of an article, with the latest revision being the first in the list
     */
    revisions: Array<ArticleV2DTO>;
};

/**
 * ArticleSearchParamsDTO
 *
 * The search parameters
 */
export type ArticleSearchParamsDTO = {
    /**
     * The search query
     */
    query?: string;
    /**
     * The ISO 639-1 language code describing language used in query-params
     */
    language?: string;
    /**
     * Return only articles with provided license. Specifying 'all' gives all articles regardless of license.
     */
    license?: string;
    /**
     * The page number of the search hits to display.
     */
    page?: number;
    /**
     * The number of search hits to display for each page.
     */
    pageSize?: number;
    /**
     * Return only articles that have one of the provided ids
     */
    ids?: Array<number>;
    /**
     * Return only articles of specific type(s)
     */
    articleTypes?: Array<string>;
    sort?: Sort;
    /**
     * Return all matched articles whether they exist on selected language or not.
     */
    fallback?: boolean;
    /**
     * A search context retrieved from the response header of a previous search.
     */
    scrollId?: string;
    /**
     * A comma separated list of codes from GREP API to filter by.
     */
    grepCodes?: Array<string>;
};

/**
 * ArticleSummaryV2DTO
 *
 * Short summary of information about the article
 */
export type ArticleSummaryV2DTO = {
    /**
     * The unique id of the article
     */
    id: number;
    /**
     * The title of the article
     */
    title: ArticleTitleDTO;
    visualElement?: VisualElementDTO;
    introduction?: ArticleIntroductionDTO;
    /**
     * A metaDescription for the article
     */
    metaDescription?: ArticleMetaDescriptionDTO;
    metaImage?: ArticleMetaImageDTO;
    /**
     * The full url to where the complete information about the article can be found
     */
    url: string;
    /**
     * Describes the license of the article
     */
    license: string;
    /**
     * The type of article this is. Possible values are frontpage-article, standard, topic-article
     */
    articleType: string;
    /**
     * The time when the article was last updated
     */
    lastUpdated: string;
    /**
     * A list of available languages for this article
     */
    supportedLanguages: Array<string>;
    /**
     * A list of codes from GREP API attached to this article
     */
    grepCodes: Array<string>;
    /**
     * Value that dictates who gets to see the article. Possible values are: everyone/teacher
     */
    availability: string;
    /**
     * Traits extracted from the article content
     */
    traits: Array<ArticleTrait>;
};

/**
 * ArticleTagDTO
 *
 * Searchable tags for the article
 */
export type ArticleTagDTO = {
    /**
     * The searchable tag.
     */
    tags: Array<string>;
    /**
     * ISO 639-1 code that represents the language used in tag
     */
    language: string;
};

/**
 * ArticleTitleDTO
 */
export type ArticleTitleDTO = {
    /**
     * The freetext title of the article
     */
    title: string;
    /**
     * The freetext html-version title of the article
     */
    htmlTitle: string;
    /**
     * ISO 639-1 code that represents the language used in title
     */
    language: string;
};

/**
 * ArticleTrait
 */
export type ArticleTrait = 'AUDIO' | 'H5P' | 'INTERACTIVE' | 'PODCAST' | 'VIDEO';

/**
 * ArticleV2DTO
 *
 * Information about the article
 */
export type ArticleV2DTO = {
    /**
     * The unique id of the article
     */
    id: number;
    /**
     * Link to article on old platform
     */
    oldNdlaUrl?: string;
    /**
     * The revision number for the article
     */
    revision: number;
    /**
     * Available titles for the article
     */
    title: ArticleTitleDTO;
    content: ArticleContentV2DTO;
    copyright: CopyrightDTO;
    tags: ArticleTagDTO;
    /**
     * Required libraries in order to render the article
     */
    requiredLibraries: Array<RequiredLibraryDTO>;
    visualElement?: VisualElementDTO;
    metaImage?: ArticleMetaImageDTO;
    introduction?: ArticleIntroductionDTO;
    /**
     * Meta description for the article
     */
    metaDescription: ArticleMetaDescriptionDTO;
    /**
     * When the article was created
     */
    created: string;
    /**
     * When the article was last updated
     */
    updated: string;
    /**
     * By whom the article was last updated
     */
    updatedBy: string;
    /**
     * When the article was last published
     */
    published: string;
    /**
     * Revision date of the article
     */
    revised: string;
    /**
     * The type of article this is. Possible values are frontpage-article, standard, topic-article
     */
    articleType: string;
    /**
     * The languages this article supports
     */
    supportedLanguages: Array<string>;
    /**
     * A list of codes from GREP API connected to the article
     */
    grepCodes: Array<string>;
    /**
     * A list of conceptIds connected to the article
     */
    conceptIds: Array<number>;
    /**
     * Value that dictates who gets to see the article. Possible values are: everyone/teacher
     */
    availability: string;
    /**
     * A list of content related to the article
     */
    relatedContent: Array<RelatedContentLinkDTO | number>;
    /**
     * The date for the next planned revision which indicates when the article might be outdated
     */
    revisionDate?: string;
    /**
     * The path to the frontpage article
     */
    slug?: string;
    disclaimer?: DisclaimerDTO;
    /**
     * Traits extracted from the article content
     */
    traits: Array<ArticleTrait>;
};

/**
 * AuthorDTO
 *
 * Information about an author
 */
export type AuthorDTO = {
    type: ContributorType;
    /**
     * The name of the of the author
     */
    name: string;
};

/**
 * ContributorType
 *
 * The description of the author. Eg. Photographer or Supplier
 */
export type ContributorType = 'artist' | 'cowriter' | 'compiler' | 'composer' | 'correction' | 'director' | 'distributor' | 'editorial' | 'facilitator' | 'idea' | 'illustrator' | 'linguistic' | 'originator' | 'photographer' | 'processor' | 'publisher' | 'reader' | 'rightsholder' | 'scriptwriter' | 'supplier' | 'translator' | 'writer';

/**
 * CopyrightDTO
 *
 * Describes the copyright information for the article
 */
export type CopyrightDTO = {
    license: LicenseDTO;
    /**
     * Reference to where the article is procured
     */
    origin?: string;
    /**
     * List of creators
     */
    creators: Array<AuthorDTO>;
    /**
     * List of processors
     */
    processors: Array<AuthorDTO>;
    /**
     * List of rightsholders
     */
    rightsholders: Array<AuthorDTO>;
    /**
     * Date from which the copyright is valid
     */
    validFrom?: string;
    /**
     * Date to which the copyright is valid
     */
    validTo?: string;
    /**
     * Whether or not the content has been processed
     */
    processed: boolean;
};

/**
 * DisclaimerDTO
 *
 * The disclaimer of the article
 */
export type DisclaimerDTO = {
    /**
     * The freetext html content of the disclaimer
     */
    disclaimer: string;
    /**
     * ISO 639-1 code that represents the language used in the disclaimer
     */
    language: string;
};

/**
 * ErrorBody
 *
 * Information about an error
 */
export type ErrorBody = {
    /**
     * Code stating the type of error
     */
    code: string;
    /**
     * Description of the error
     */
    description: string;
    /**
     * When the error occurred
     */
    occurredAt: string;
    /**
     * Numeric http status code
     */
    statusCode: number;
};

/**
 * LicenseDTO
 *
 * Describes the license of the article
 */
export type LicenseDTO = {
    /**
     * The name of the license
     */
    license: string;
    /**
     * Description of the license
     */
    description?: string;
    /**
     * Url to where the license can be found
     */
    url?: string;
};

/**
 * NotFoundWithSupportedLanguages
 *
 * Information about an error
 */
export type NotFoundWithSupportedLanguages = {
    /**
     * Code stating the type of error
     */
    code: string;
    /**
     * Description of the error
     */
    description: string;
    /**
     * When the error occurred
     */
    occurredAt: string;
    /**
     * List of supported languages
     */
    supportedLanguages?: Array<string>;
    /**
     * Numeric http status code
     */
    statusCode: number;
};

/**
 * RelatedContentLinkDTO
 *
 * External link related to the article
 */
export type RelatedContentLinkDTO = {
    /**
     * Title of the article
     */
    title: string;
    /**
     * The url to where the article can be viewed
     */
    url: string;
};

/**
 * RequiredLibraryDTO
 *
 * Information about a library required to render the article
 */
export type RequiredLibraryDTO = {
    /**
     * The type of the library. E.g. CSS or JavaScript
     */
    mediaType: string;
    /**
     * The name of the library
     */
    name: string;
    /**
     * The full url to where the library can be downloaded
     */
    url: string;
};

/**
 * SearchResultV2DTO
 *
 * Information about search-results
 */
export type SearchResultV2DTO = {
    /**
     * The total number of articles matching this query
     */
    totalCount: number;
    /**
     * For which page results are shown from
     */
    page?: number;
    /**
     * The number of results per page
     */
    pageSize: number;
    /**
     * The chosen search language
     */
    language: string;
    /**
     * The search results
     */
    results: Array<ArticleSummaryV2DTO>;
};

/**
 * Sort
 *
 * The sorting used on results. Default is by -relevance.
 */
export type Sort = '-relevance' | 'relevance' | '-title' | 'title' | '-lastUpdated' | 'lastUpdated' | '-id' | 'id';

/**
 * TagsSearchResultDTO
 *
 * Information about tags-search-results
 */
export type TagsSearchResultDTO = {
    /**
     * The total number of tags matching this query
     */
    totalCount: number;
    /**
     * For which page results are shown from
     */
    page: number;
    /**
     * The number of results per page
     */
    pageSize: number;
    /**
     * The chosen search language
     */
    language: string;
    /**
     * The search results
     */
    results: Array<string>;
};

/**
 * ValidationErrorBody
 *
 * Information about an error
 */
export type ValidationErrorBody = {
    /**
     * Code stating the type of error
     */
    code: string;
    /**
     * Description of the error
     */
    description: string;
    /**
     * When the error occurred
     */
    occurredAt: string;
    /**
     * List of validation messages
     */
    messages?: Array<ValidationMessage>;
    /**
     * Numeric http status code
     */
    statusCode: number;
};

/**
 * ValidationMessage
 *
 * A message describing a validation error on a specific field
 */
export type ValidationMessage = {
    /**
     * The field the error occured in
     */
    field: string;
    /**
     * The validation message
     */
    message: string;
};

/**
 * VisualElementDTO
 *
 * A visual element article
 */
export type VisualElementDTO = {
    /**
     * Html containing the visual element. May contain any legal html element, including the embed-tag
     */
    visualElement: string;
    /**
     * The ISO 639-1 language code describing which article translation this visual element belongs to
     */
    language: string;
};

export type GetArticleApiV2ArticlesTagSearchData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return only articles with content matching the specified query.
         */
        query?: string;
        /**
         * The number of search hits to display for each page.
         */
        'page-size'?: number;
        /**
         * The page number of the search hits to display.
         */
        page?: number;
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
    };
    url: '/article-api/v2/articles/tag-search';
};

export type GetArticleApiV2ArticlesTagSearchErrors = {
    400: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetArticleApiV2ArticlesTagSearchError = GetArticleApiV2ArticlesTagSearchErrors[keyof GetArticleApiV2ArticlesTagSearchErrors];

export type GetArticleApiV2ArticlesTagSearchResponses = {
    200: TagsSearchResultDTO;
};

export type GetArticleApiV2ArticlesTagSearchResponse = GetArticleApiV2ArticlesTagSearchResponses[keyof GetArticleApiV2ArticlesTagSearchResponses];

export type GetArticleApiV2ArticlesIdsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return only articles that have one of the provided ids. To provide multiple ids, separate by comma (,).
         */
        ids?: Array<number>;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * The number of search hits to display for each page.
         */
        'page-size'?: number;
        /**
         * The page number of the search hits to display.
         */
        page?: number;
    };
    url: '/article-api/v2/articles/ids';
};

export type GetArticleApiV2ArticlesIdsErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetArticleApiV2ArticlesIdsError = GetArticleApiV2ArticlesIdsErrors[keyof GetArticleApiV2ArticlesIdsErrors];

export type GetArticleApiV2ArticlesIdsResponses = {
    200: Array<ArticleV2DTO>;
};

export type GetArticleApiV2ArticlesIdsResponse = GetArticleApiV2ArticlesIdsResponses[keyof GetArticleApiV2ArticlesIdsResponses];

export type GetArticleApiV2ArticlesSlugRssXmlData = {
    body?: never;
    path: {
        /**
         * Slug of the article to generate RSS for
         */
        slug: string;
    };
    query?: never;
    url: '/article-api/v2/articles/{slug}/rss.xml';
};

export type GetArticleApiV2ArticlesSlugRssXmlErrors = {
    400: AllErrors;
    404: AllErrors;
    410: AllErrors;
    default: AllErrors;
};

export type GetArticleApiV2ArticlesSlugRssXmlError = GetArticleApiV2ArticlesSlugRssXmlErrors[keyof GetArticleApiV2ArticlesSlugRssXmlErrors];

export type GetArticleApiV2ArticlesSlugRssXmlResponses = {
    200: string;
};

export type GetArticleApiV2ArticlesSlugRssXmlResponse = GetArticleApiV2ArticlesSlugRssXmlResponses[keyof GetArticleApiV2ArticlesSlugRssXmlResponses];

export type GetArticleApiV2ArticlesArticleIdData = {
    body?: never;
    path: {
        /**
         * Id or slug of the article that is to be fetched.
         */
        article_id: string;
    };
    query?: {
        /**
         * Revision of article to fetch. If not provided the current revision is returned.
         */
        revision?: number;
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
    };
    url: '/article-api/v2/articles/{article_id}';
};

export type GetArticleApiV2ArticlesArticleIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    410: AllErrors;
    default: AllErrors;
};

export type GetArticleApiV2ArticlesArticleIdError = GetArticleApiV2ArticlesArticleIdErrors[keyof GetArticleApiV2ArticlesArticleIdErrors];

export type GetArticleApiV2ArticlesArticleIdResponses = {
    200: ArticleV2DTO;
};

export type GetArticleApiV2ArticlesArticleIdResponse = GetArticleApiV2ArticlesArticleIdResponses[keyof GetArticleApiV2ArticlesArticleIdResponses];

export type GetArticleApiV2ArticlesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return only articles with content matching the specified query.
         */
        query?: string;
        /**
         * Return only articles of specific type(s). To provide multiple types, separate by comma (,).
         */
        articleTypes?: Array<string>;
        /**
         * Return only articles that have one of the provided ids. To provide multiple ids, separate by comma (,).
         */
        ids?: Array<number>;
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Return only results with provided license. Specifying 'all' gives all articles regardless of licence.
         */
        license?: string;
        /**
         * The page number of the search hits to display.
         */
        page?: number;
        /**
         * The number of search hits to display for each page.
         */
        'page-size'?: number;
        /**
         * The sorting used on results.
         * The following are supported: -relevance, relevance, -title, title, -lastUpdated, lastUpdated, -id, id.
         * Default is by -relevance (desc) when query is set, and id (asc) when query is empty.
         */
        sort?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
        /**
         * A unique string obtained from a search you want to keep scrolling in. To obtain one from a search, provide one of the following values: [0,initial,start,first].
         * When scrolling, the parameters from the initial search is used, except in the case of 'language' and 'fallback'.
         * This value may change between scrolls. Always use the one in the latest scroll result (The context, if unused, dies after 1m).
         * If you are not paginating past 10000 hits, you can ignore this and use 'page' and 'page-size' instead.
         *
         */
        'search-context'?: string;
        /**
         * A comma separated list of codes from GREP API the resources should be filtered by.
         */
        'grep-codes'?: Array<string>;
    };
    url: '/article-api/v2/articles';
};

export type GetArticleApiV2ArticlesErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetArticleApiV2ArticlesError = GetArticleApiV2ArticlesErrors[keyof GetArticleApiV2ArticlesErrors];

export type GetArticleApiV2ArticlesResponses = {
    200: SearchResultV2DTO;
};

export type GetArticleApiV2ArticlesResponse = GetArticleApiV2ArticlesResponses[keyof GetArticleApiV2ArticlesResponses];

export type PostArticleApiV2ArticlesSearchData = {
    body: ArticleSearchParamsDTO;
    path?: never;
    query?: never;
    url: '/article-api/v2/articles/search';
};

export type PostArticleApiV2ArticlesSearchErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PostArticleApiV2ArticlesSearchError = PostArticleApiV2ArticlesSearchErrors[keyof PostArticleApiV2ArticlesSearchErrors];

export type PostArticleApiV2ArticlesSearchResponses = {
    200: SearchResultV2DTO;
};

export type PostArticleApiV2ArticlesSearchResponse = PostArticleApiV2ArticlesSearchResponses[keyof PostArticleApiV2ArticlesSearchResponses];

export type GetArticleApiV2ArticlesArticleIdRevisionsData = {
    body?: never;
    path: {
        /**
         * Id or slug of the article that is to be fetched.
         */
        article_id: number;
    };
    query?: never;
    url: '/article-api/v2/articles/{article_id}/revisions';
};

export type GetArticleApiV2ArticlesArticleIdRevisionsErrors = {
    400: AllErrors;
    404: AllErrors;
    500: AllErrors;
    default: AllErrors;
};

export type GetArticleApiV2ArticlesArticleIdRevisionsError = GetArticleApiV2ArticlesArticleIdRevisionsErrors[keyof GetArticleApiV2ArticlesArticleIdRevisionsErrors];

export type GetArticleApiV2ArticlesArticleIdRevisionsResponses = {
    200: Array<number>;
};

export type GetArticleApiV2ArticlesArticleIdRevisionsResponse = GetArticleApiV2ArticlesArticleIdRevisionsResponses[keyof GetArticleApiV2ArticlesArticleIdRevisionsResponses];

export type GetArticleApiV2ArticlesExternalIdDeprecatedNodeIdData = {
    body?: never;
    path: {
        /**
         * Id of deprecated NDLA node
         */
        deprecated_node_id: string;
    };
    query?: never;
    url: '/article-api/v2/articles/external_id/{deprecated_node_id}';
};

export type GetArticleApiV2ArticlesExternalIdDeprecatedNodeIdErrors = {
    400: AllErrors;
    404: AllErrors;
    500: AllErrors;
    default: AllErrors;
};

export type GetArticleApiV2ArticlesExternalIdDeprecatedNodeIdError = GetArticleApiV2ArticlesExternalIdDeprecatedNodeIdErrors[keyof GetArticleApiV2ArticlesExternalIdDeprecatedNodeIdErrors];

export type GetArticleApiV2ArticlesExternalIdDeprecatedNodeIdResponses = {
    200: ArticleIdV2DTO;
};

export type GetArticleApiV2ArticlesExternalIdDeprecatedNodeIdResponse = GetArticleApiV2ArticlesExternalIdDeprecatedNodeIdResponses[keyof GetArticleApiV2ArticlesExternalIdDeprecatedNodeIdResponses];

export type GetArticleApiV2ArticlesExternalIdsDeprecatedNodeIdData = {
    body?: never;
    path: {
        /**
         * Id of deprecated NDLA node
         */
        deprecated_node_id: string;
    };
    query?: never;
    url: '/article-api/v2/articles/external_ids/{deprecated_node_id}';
};

export type GetArticleApiV2ArticlesExternalIdsDeprecatedNodeIdErrors = {
    400: AllErrors;
    404: AllErrors;
    500: AllErrors;
    default: AllErrors;
};

export type GetArticleApiV2ArticlesExternalIdsDeprecatedNodeIdError = GetArticleApiV2ArticlesExternalIdsDeprecatedNodeIdErrors[keyof GetArticleApiV2ArticlesExternalIdsDeprecatedNodeIdErrors];

export type GetArticleApiV2ArticlesExternalIdsDeprecatedNodeIdResponses = {
    200: ArticleIdsDTO;
};

export type GetArticleApiV2ArticlesExternalIdsDeprecatedNodeIdResponse = GetArticleApiV2ArticlesExternalIdsDeprecatedNodeIdResponses[keyof GetArticleApiV2ArticlesExternalIdsDeprecatedNodeIdResponses];

export type GetArticleApiV2ArticlesArticleIdRevisionHistoryData = {
    body?: never;
    path: {
        /**
         * Id or slug of the article that is to be fetched.
         */
        article_id: number;
    };
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
    };
    url: '/article-api/v2/articles/{article_id}/revision-history';
};

export type GetArticleApiV2ArticlesArticleIdRevisionHistoryErrors = {
    400: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetArticleApiV2ArticlesArticleIdRevisionHistoryError = GetArticleApiV2ArticlesArticleIdRevisionHistoryErrors[keyof GetArticleApiV2ArticlesArticleIdRevisionHistoryErrors];

export type GetArticleApiV2ArticlesArticleIdRevisionHistoryResponses = {
    200: ArticleRevisionHistoryDTO;
};

export type GetArticleApiV2ArticlesArticleIdRevisionHistoryResponse = GetArticleApiV2ArticlesArticleIdRevisionHistoryResponses[keyof GetArticleApiV2ArticlesArticleIdRevisionHistoryResponses];
