// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetOembedProxyV1OembedData, GetOembedProxyV1OembedErrors, GetOembedProxyV1OembedResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Returns oEmbed information for a given url.
 *
 * Returns oEmbed information for a given url.
 */
export const getOembedProxyV1Oembed = <ThrowOnError extends boolean = false>(options: Options<GetOembedProxyV1OembedData, ThrowOnError>): RequestResult<GetOembedProxyV1OembedResponses, GetOembedProxyV1OembedErrors, ThrowOnError> => (options.client ?? client).get<GetOembedProxyV1OembedResponses, GetOembedProxyV1OembedErrors, ThrowOnError>({ url: '/oembed-proxy/v1/oembed', ...options });
