// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AiGenerated
 */
export type AiGenerated = 'No' | 'Partial' | 'Yes';

/**
 * AllErrors
 */
export type AllErrors = ErrorBody | NotFoundWithSupportedLanguages | ValidationErrorBody;

/**
 * AuthorDTO
 *
 * Information about an author
 */
export type AuthorDTO = {
    type: ContributorType;
    /**
     * The name of the of the author
     */
    name: string;
};

/**
 * BatchMetaDataAndFileForm
 */
export type BatchMetaDataAndFileForm = {
    metadatas: Array<NewImageMetaInformationV2DTO>;
    files: Array<Blob | File>;
};

/**
 * BulkUploadItemDTO
 */
export type BulkUploadItemDTO = {
    fileName?: string;
    status: BulkUploadItemStatus;
    image?: ImageMetaInformationV3DTO;
    error?: string;
};

/**
 * BulkUploadItemStatus
 */
export type BulkUploadItemStatus = 'Done' | 'Failed' | 'Pending' | 'Uploading';

/**
 * BulkUploadStartedDTO
 *
 * Identifier returned when a bulk upload session has been started
 */
export type BulkUploadStartedDTO = {
    /**
     * Identifier used to track the bulk upload via the status endpoint
     */
    uploadId: string;
};

/**
 * BulkUploadStateDTO
 */
export type BulkUploadStateDTO = {
    status: BulkUploadStatus;
    total: number;
    completed: number;
    failed: number;
    items: Array<BulkUploadItemDTO>;
    error?: string;
};

/**
 * BulkUploadStatus
 */
export type BulkUploadStatus = 'Complete' | 'Failed' | 'Pending' | 'Running';

/**
 * ContributorType
 *
 * The description of the author. Eg. Photographer or Supplier
 */
export type ContributorType = 'artist' | 'cowriter' | 'compiler' | 'composer' | 'correction' | 'director' | 'distributor' | 'editorial' | 'facilitator' | 'idea' | 'illustrator' | 'linguistic' | 'originator' | 'photographer' | 'processor' | 'publisher' | 'reader' | 'rightsholder' | 'scriptwriter' | 'supplier' | 'translator' | 'writer';

/**
 * CopyMetaDataAndFileForm
 */
export type CopyMetaDataAndFileForm = {
    file: Blob | File;
};

/**
 * CopyrightDTO
 *
 * Describes the copyright information for the image
 */
export type CopyrightDTO = {
    license: LicenseDTO;
    /**
     * Reference to where the article is procured
     */
    origin?: string;
    /**
     * List of creators
     */
    creators: Array<AuthorDTO>;
    /**
     * List of processors
     */
    processors: Array<AuthorDTO>;
    /**
     * List of rightsholders
     */
    rightsholders: Array<AuthorDTO>;
    /**
     * Date from which the copyright is valid
     */
    validFrom?: string;
    /**
     * Date to which the copyright is valid
     */
    validTo?: string;
    /**
     * Whether or not the content has been processed
     */
    processed: boolean;
};

/**
 * EditorNoteDTO
 *
 * Note about a change that happened to the image
 */
export type EditorNoteDTO = {
    /**
     * Timestamp of the change
     */
    timestamp: string;
    /**
     * Who triggered the change
     */
    updatedBy: string;
    /**
     * Editorial note
     */
    note: string;
};

/**
 * ErrorBody
 *
 * Information about an error
 */
export type ErrorBody = {
    /**
     * Code stating the type of error
     */
    code: string;
    /**
     * Description of the error
     */
    description: string;
    /**
     * When the error occurred
     */
    occurredAt: string;
    /**
     * Numeric http status code
     */
    statusCode: number;
};

/**
 * ImageAltTextDTO
 */
export type ImageAltTextDTO = {
    /**
     * The alternative text for the image
     */
    alttext: string;
    /**
     * ISO 639-1 code that represents the language used in the alternative text
     */
    language: string;
};

/**
 * ImageCaptionDTO
 */
export type ImageCaptionDTO = {
    /**
     * The caption for the image
     */
    caption: string;
    /**
     * ISO 639-1 code that represents the language used in the caption
     */
    language: string;
};

/**
 * ImageContentType
 */
export type ImageContentType = 'image/bmp' | 'image/gif' | 'image/jpeg' | 'image/x-citrix-jpeg' | 'image/pjpeg' | 'image/png' | 'image/x-png' | 'image/svg+xml' | 'image/webp';

/**
 * ImageDimensionsDTO
 *
 * Dimensions of the image
 */
export type ImageDimensionsDTO = {
    /**
     * The width of the image in pixels
     */
    width: number;
    /**
     * The height of the image in pixels
     */
    height: number;
};

/**
 * ImageEditorsDTO
 *
 * A list of image editors
 */
export type ImageEditorsDTO = {
    /**
     * The user ids of the editors
     */
    ids?: Array<string>;
};

/**
 * ImageFileDTO
 *
 * Describes the image file
 */
export type ImageFileDTO = {
    /**
     * File name pointing to image file
     */
    fileName: string;
    /**
     * The size of the image in bytes
     */
    size: number;
    /**
     * The mimetype of the image
     */
    contentType: ImageContentType;
    /**
     * The full url to where the image can be downloaded
     */
    imageUrl: string;
    dimensions?: ImageDimensionsDTO;
    /**
     * Size variants of the image
     */
    variants: Array<ImageVariantDTO>;
    /**
     * ISO 639-1 code that represents the language used in the caption
     */
    language: string;
    /**
     * Date image was taken, if available
     */
    originalDate?: string;
};

/**
 * ImageMetaInformationV2DTO
 *
 * Meta information for the image
 */
export type ImageMetaInformationV2DTO = {
    /**
     * The unique id of the image
     */
    id: string;
    /**
     * The url to where this information can be found
     */
    metaUrl: string;
    /**
     * The title for the image
     */
    title: ImageTitleDTO;
    /**
     * Alternative text for the image
     */
    alttext: ImageAltTextDTO;
    /**
     * The full url to where the image can be downloaded
     */
    imageUrl: string;
    /**
     * The size of the image in bytes
     */
    size: number;
    /**
     * The mimetype of the image
     */
    contentType: ImageContentType;
    copyright: CopyrightDTO;
    tags: ImageTagDTO;
    /**
     * Searchable caption for the image
     */
    caption: ImageCaptionDTO;
    /**
     * Supported languages for the image title, alt-text, tags and caption.
     */
    supportedLanguages: Array<string>;
    /**
     * Describes when the image was created
     */
    created: string;
    /**
     * Describes who created the image
     */
    createdBy: string;
    /**
     * Describes if the model has released use of the image
     */
    modelRelease: ModelReleasedStatus;
    /**
     * Describes the changes made to the image, only visible to editors
     */
    editorNotes?: Array<EditorNoteDTO>;
    imageDimensions?: ImageDimensionsDTO;
};

/**
 * ImageMetaInformationV3DTO
 *
 * Meta information for the image
 */
export type ImageMetaInformationV3DTO = {
    /**
     * The unique id of the image
     */
    id: string;
    /**
     * The url to where this information can be found
     */
    metaUrl: string;
    /**
     * The title for the image
     */
    title: ImageTitleDTO;
    /**
     * Alternative text for the image
     */
    alttext: ImageAltTextDTO;
    copyright: CopyrightDTO;
    tags: ImageTagDTO;
    /**
     * Searchable caption for the image
     */
    caption: ImageCaptionDTO;
    /**
     * Supported languages for the image title, alt-text, tags and caption.
     */
    supportedLanguages: Array<string>;
    /**
     * Describes when the image was created
     */
    created: string;
    /**
     * Describes who created the image
     */
    createdBy: string;
    /**
     * Describes if the model has released use of the image
     */
    modelRelease: ModelReleasedStatus;
    /**
     * Describes the changes made to the image, only visible to editors
     */
    editorNotes?: Array<EditorNoteDTO>;
    image: ImageFileDTO;
    /**
     * Describes if the image is inactive or not
     */
    inactive: boolean;
    /**
     * Describes whether the image is AI generated
     */
    aiGenerated?: AiGenerated;
};

/**
 * ImageMetaSummaryDTO
 *
 * Summary of meta information for an image
 */
export type ImageMetaSummaryDTO = {
    /**
     * The unique id of the image
     */
    id: string;
    /**
     * The title for this image
     */
    title: ImageTitleDTO;
    /**
     * The copyright authors for this image
     */
    contributors: Array<string>;
    /**
     * The alt text for this image
     */
    altText: ImageAltTextDTO;
    /**
     * The caption for this image
     */
    caption: ImageCaptionDTO;
    /**
     * The full url to where a preview of the image can be downloaded
     */
    previewUrl: string;
    /**
     * The full url to where the complete metainformation about the image can be found
     */
    metaUrl: string;
    /**
     * Describes the license of the image
     */
    license: string;
    /**
     * List of supported languages in priority
     */
    supportedLanguages: Array<string>;
    /**
     * Describes if the model has released use of the image
     */
    modelRelease: ModelReleasedStatus;
    /**
     * Describes if the image is AI generated
     */
    aiGenerated?: AiGenerated;
    /**
     * Describes the changes made to the image, only visible to editors
     */
    editorNotes?: Array<string>;
    /**
     * The time and date of last update
     */
    lastUpdated: string;
    /**
     * The size of the image in bytes
     */
    fileSize: number;
    /**
     * The mimetype of the image
     */
    contentType: string;
    imageDimensions?: ImageDimensionsDTO;
    /**
     * Whether the image is inactive or not
     */
    inactive: boolean;
};

/**
 * ImageSearchField
 */
export type ImageSearchField = 'alttexts' | 'captions' | 'creators' | 'editorNotes' | 'processors' | 'rightsholders' | 'tags' | 'titles';

/**
 * ImageTagDTO
 *
 * Searchable tags for the image
 */
export type ImageTagDTO = {
    /**
     * The searchable tag.
     */
    tags: Array<string>;
    /**
     * ISO 639-1 code that represents the language used in tag
     */
    language: string;
};

/**
 * ImageTitleDTO
 */
export type ImageTitleDTO = {
    /**
     * The freetext title of the image
     */
    title: string;
    /**
     * ISO 639-1 code that represents the language used in title
     */
    language: string;
};

/**
 * ImageVariantDTO
 */
export type ImageVariantDTO = {
    size: ImageVariantSize;
    /**
     * The full URL to where the image variant can be downloaded
     */
    variantUrl: string;
};

/**
 * ImageVariantSize
 *
 * The named size of this image variant
 */
export type ImageVariantSize = 'icon' | 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge' | 'xxlarge';

/**
 * LicenseDTO
 *
 * Describes the license of the article
 */
export type LicenseDTO = {
    /**
     * The name of the license
     */
    license: string;
    /**
     * Description of the license
     */
    description?: string;
    /**
     * Url to where the license can be found
     */
    url?: string;
};

/**
 * MetaDataAndFileForm
 */
export type MetaDataAndFileForm = {
    metadata: NewImageMetaInformationV2DTO;
    file: Blob | File;
};

/**
 * ModelReleasedStatus
 */
export type ModelReleasedStatus = 'no' | 'not-applicable' | 'not-set' | 'yes';

/**
 * NewImageMetaInformationV2DTO
 *
 * Meta information for the image
 */
export type NewImageMetaInformationV2DTO = {
    /**
     * Title for the image
     */
    title: string;
    /**
     * Alternative text for the image
     */
    alttext?: string;
    copyright: CopyrightDTO;
    /**
     * Searchable tags for the image
     */
    tags: Array<string>;
    /**
     * Caption for the image
     */
    caption: string;
    /**
     * ISO 639-1 code that represents the language used in the caption
     */
    language: string;
    /**
     * Describes if the model has released use of the image, defaults to 'no'
     */
    modelReleased?: ModelReleasedStatus;
    /**
     * Describes whether the image is AI generated
     */
    aiGenerated?: AiGenerated;
};

/**
 * NotFoundWithSupportedLanguages
 *
 * Information about an error
 */
export type NotFoundWithSupportedLanguages = {
    /**
     * Code stating the type of error
     */
    code: string;
    /**
     * Description of the error
     */
    description: string;
    /**
     * When the error occurred
     */
    occurredAt: string;
    /**
     * List of supported languages
     */
    supportedLanguages?: Array<string>;
    /**
     * Numeric http status code
     */
    statusCode: number;
};

/**
 * SearchParamsDTO
 *
 * The search parameters
 */
export type SearchParamsDTO = {
    /**
     * Return only images matching the specified query.
     */
    query?: string;
    /**
     * Restrict query searches to the specified fields. If omitted or empty, all the fields are used.
     */
    queryFields?: Array<ImageSearchField>;
    /**
     * Return only images with provided license. Specifying 'all' gives all images regardless of license.
     */
    license?: string;
    /**
     * The ISO 639-1 language code describing language used in query-params
     */
    language?: string;
    /**
     * Fallback to existing language if language is specified.
     */
    fallback?: boolean;
    /**
     * Return only images with full size larger than submitted value in bytes.
     */
    minimumSize?: number;
    /**
     * Return copyrighted images. May be omitted.
     *
     * @deprecated
     */
    includeCopyrighted?: boolean;
    sort?: Sort;
    /**
     * The page number of the search hits to display.
     */
    page?: number;
    /**
     * The number of search hits to display for each page.
     */
    pageSize?: number;
    /**
     * Only show podcast friendly images. Same width and height, and between 1400 and 3000 pixels.
     */
    podcastFriendly?: boolean;
    /**
     * A search context retrieved from the response header of a previous search.
     */
    scrollId?: string;
    /**
     * Include inactive images
     */
    inactive?: boolean;
    /**
     * Return only images with one of the provided values for modelReleased.
     */
    modelReleased?: Array<ModelReleasedStatus>;
    /**
     * Return only images with one of the provided values for aiGenerated.
     */
    aiGenerated?: Array<AiGenerated>;
    /**
     * Filter editors of the image(s). Multiple values can be specified in a comma separated list.
     */
    users?: Array<string>;
    /**
     * Filter images with width greater than or equal to this value.
     */
    widthFrom?: number;
    /**
     * Filter images with width less than or equal to this value.
     */
    widthTo?: number;
    /**
     * Filter images with height greater than or equal to this value.
     */
    heightFrom?: number;
    /**
     * Filter images with height less than or equal to this value.
     */
    heightTo?: number;
    /**
     * Filter images by content type (e.g., 'image/jpeg', 'image/png').
     */
    contentType?: ImageContentType;
};

/**
 * SearchResultDTO
 *
 * Information about search-results
 */
export type SearchResultDTO = {
    /**
     * The total number of images matching this query
     */
    totalCount: number;
    /**
     * For which page results are shown from
     */
    page?: number;
    /**
     * The number of results per page
     */
    pageSize: number;
    /**
     * The chosen search language
     */
    language: string;
    /**
     * The search results
     */
    results: Array<ImageMetaSummaryDTO>;
};

/**
 * SearchResultV3DTO
 *
 * Information about search-results
 */
export type SearchResultV3DTO = {
    /**
     * The total number of images matching this query
     */
    totalCount: number;
    /**
     * For which page results are shown from
     */
    page?: number;
    /**
     * The number of results per page
     */
    pageSize: number;
    /**
     * The chosen search language
     */
    language: string;
    /**
     * The search results
     */
    results: Array<ImageMetaInformationV3DTO>;
};

/**
 * Sort
 *
 * The sorting used on results. The following are supported: relevance, -relevance, title, -title, lastUpdated, -lastUpdated, id, -id. Default is by -relevance (desc) when query is set, and title (asc) when query is empty.
 */
export type Sort = '-relevance' | 'relevance' | '-title' | 'title' | '-lastUpdated' | 'lastUpdated' | '-id' | 'id' | '-width' | 'width' | '-height' | 'height';

/**
 * TagsSearchResultDTO
 *
 * Information about tags-search-results
 */
export type TagsSearchResultDTO = {
    /**
     * The total number of tags matching this query
     */
    totalCount: number;
    /**
     * For which page results are shown from
     */
    page: number;
    /**
     * The number of results per page
     */
    pageSize: number;
    /**
     * The chosen search language
     */
    language: string;
    /**
     * The search results
     */
    results: Array<string>;
};

/**
 * UpdateImageMetaInformationDTO
 *
 * Meta information for the image
 */
export type UpdateImageMetaInformationDTO = {
    /**
     * ISO 639-1 code that represents the language
     */
    language: string;
    /**
     * Title for the image
     */
    title?: string;
    /**
     * Alternative text for the image
     */
    alttext?: string | null;
    copyright?: CopyrightDTO;
    /**
     * Searchable tags for the image
     */
    tags?: Array<string>;
    /**
     * Caption for the image
     */
    caption?: string;
    /**
     * Describes if the model has released use of the image
     */
    modelReleased?: ModelReleasedStatus;
    /**
     * Whether the image is inactive
     */
    inactive?: boolean;
    /**
     * Describes whether the image is AI generated
     */
    aiGenerated?: AiGenerated;
};

/**
 * UpdateMetaDataAndFileForm
 */
export type UpdateMetaDataAndFileForm = {
    metadata: UpdateImageMetaInformationDTO;
    file?: Blob | File;
};

/**
 * ValidationErrorBody
 *
 * Information about an error
 */
export type ValidationErrorBody = {
    /**
     * Code stating the type of error
     */
    code: string;
    /**
     * Description of the error
     */
    description: string;
    /**
     * When the error occurred
     */
    occurredAt: string;
    /**
     * List of validation messages
     */
    messages?: Array<ValidationMessage>;
    /**
     * Numeric http status code
     */
    statusCode: number;
};

/**
 * ValidationMessage
 *
 * A message describing a validation error on a specific field
 */
export type ValidationMessage = {
    /**
     * The field the error occured in
     */
    field: string;
    /**
     * The validation message
     */
    message: string;
};

export type GetImageApiV2ImagesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return only images with titles, alt-texts or tags matching the specified query.
         */
        query?: string;
        /**
         * Restrict query searches to the specified fields. If omitted or empty, all the fields are used.
         */
        'query-fields'?: Array<ImageSearchField>;
        /**
         * Return only images with full size larger than submitted value in bytes.
         */
        'minimum-size'?: number;
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
        /**
         * Return only images with provided license. Specifying 'all' gives all images regardless of license.
         */
        license?: string;
        /**
         * The sorting used on results.
         * The following are supported: -relevance, relevance, -title, title, -lastUpdated, lastUpdated, -id, id, -width, width, -height, height.
         * Default is by -relevance (desc) when query is set, and title (asc) when query is empty.
         */
        sort?: string;
        /**
         * The page number of the search hits to display.
         */
        page?: number;
        /**
         * The number of search hits to display for each page. Defaults to 10 and max is 10000.
         */
        'page-size'?: number;
        /**
         * Filter images that are podcast friendly. Width==heigth and between 1400 and 3000.
         */
        'podcast-friendly'?: boolean;
        /**
         * A unique string obtained from a search you want to keep scrolling in. To obtain one from a search, provide one of the following values: [0,initial,start,first].
         * When scrolling, the parameters from the initial search is used, except in the case of 'language'.
         * This value may change between scrolls. Always use the one in the latest scroll result (The context, if unused, dies after 1m).
         * If you are not paginating past 10000 hits, you can ignore this and use 'page' and 'page-size' instead.
         *
         */
        'search-context'?: string;
        /**
         * Filter whether the image(s) should be model-released or not. Multiple values can be specified in a comma separated list. Possible values include: yes,no,not-applicable,not-set
         */
        'model-released'?: Array<ModelReleasedStatus>;
        /**
         * Filter whether the image(s) is AI generated or not. Multiple values can be specified in a comma separated list. Possible values include: Partial,Yes,No
         */
        'ai-generated'?: Array<AiGenerated>;
        /**
         * Include inactive images
         */
        inactive?: boolean;
        /**
         * Filter images with width greater than or equal to this value.
         */
        'width-from'?: number;
        /**
         * Filter images with width less than or equal to this value.
         */
        'width-to'?: number;
        /**
         * Filter images with height greater than or equal to this value.
         */
        'height-from'?: number;
        /**
         * Filter images with height less than or equal to this value.
         */
        'height-to'?: number;
        /**
         * Filter images by content type (e.g., 'image/jpeg', 'image/png').
         */
        'content-type'?: string;
    };
    url: '/image-api/v2/images';
};

export type GetImageApiV2ImagesErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetImageApiV2ImagesError = GetImageApiV2ImagesErrors[keyof GetImageApiV2ImagesErrors];

export type GetImageApiV2ImagesResponses = {
    200: SearchResultDTO;
};

export type GetImageApiV2ImagesResponse = GetImageApiV2ImagesResponses[keyof GetImageApiV2ImagesResponses];

export type PostImageApiV2ImagesData = {
    body: MetaDataAndFileForm;
    path?: never;
    query?: never;
    url: '/image-api/v2/images';
};

export type PostImageApiV2ImagesErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    413: AllErrors;
    default: AllErrors;
};

export type PostImageApiV2ImagesError = PostImageApiV2ImagesErrors[keyof PostImageApiV2ImagesErrors];

export type PostImageApiV2ImagesResponses = {
    200: ImageMetaInformationV2DTO;
};

export type PostImageApiV2ImagesResponse = PostImageApiV2ImagesResponses[keyof PostImageApiV2ImagesResponses];

export type GetImageApiV2ImagesTagSearchData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return only images with titles, alt-texts or tags matching the specified query.
         */
        query?: string;
        /**
         * The number of search hits to display for each page. Defaults to 10 and max is 10000.
         */
        'page-size'?: number;
        /**
         * The page number of the search hits to display.
         */
        page?: number;
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * The sorting used on results.
         * The following are supported: -relevance, relevance, -title, title, -lastUpdated, lastUpdated, -id, id, -width, width, -height, height.
         * Default is by -relevance (desc) when query is set, and title (asc) when query is empty.
         */
        sort?: string;
    };
    url: '/image-api/v2/images/tag-search';
};

export type GetImageApiV2ImagesTagSearchErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetImageApiV2ImagesTagSearchError = GetImageApiV2ImagesTagSearchErrors[keyof GetImageApiV2ImagesTagSearchErrors];

export type GetImageApiV2ImagesTagSearchResponses = {
    200: TagsSearchResultDTO;
};

export type GetImageApiV2ImagesTagSearchResponse = GetImageApiV2ImagesTagSearchResponses[keyof GetImageApiV2ImagesTagSearchResponses];

export type PostImageApiV2ImagesSearchData = {
    body: SearchParamsDTO;
    path?: never;
    query?: never;
    url: '/image-api/v2/images/search';
};

export type PostImageApiV2ImagesSearchErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PostImageApiV2ImagesSearchError = PostImageApiV2ImagesSearchErrors[keyof PostImageApiV2ImagesSearchErrors];

export type PostImageApiV2ImagesSearchResponses = {
    200: SearchResultDTO;
};

export type PostImageApiV2ImagesSearchResponse = PostImageApiV2ImagesSearchResponses[keyof PostImageApiV2ImagesSearchResponses];

export type DeleteImageApiV2ImagesImageIdData = {
    body?: never;
    path: {
        /**
         * Image_id of the image that needs to be fetched.
         */
        image_id: number;
    };
    query?: never;
    url: '/image-api/v2/images/{image_id}';
};

export type DeleteImageApiV2ImagesImageIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type DeleteImageApiV2ImagesImageIdError = DeleteImageApiV2ImagesImageIdErrors[keyof DeleteImageApiV2ImagesImageIdErrors];

export type DeleteImageApiV2ImagesImageIdResponses = {
    204: void;
};

export type DeleteImageApiV2ImagesImageIdResponse = DeleteImageApiV2ImagesImageIdResponses[keyof DeleteImageApiV2ImagesImageIdResponses];

export type GetImageApiV2ImagesImageIdData = {
    body?: never;
    path: {
        /**
         * Image_id of the image that needs to be fetched.
         */
        image_id: number;
    };
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
    };
    url: '/image-api/v2/images/{image_id}';
};

export type GetImageApiV2ImagesImageIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetImageApiV2ImagesImageIdError = GetImageApiV2ImagesImageIdErrors[keyof GetImageApiV2ImagesImageIdErrors];

export type GetImageApiV2ImagesImageIdResponses = {
    200: ImageMetaInformationV2DTO;
};

export type GetImageApiV2ImagesImageIdResponse = GetImageApiV2ImagesImageIdResponses[keyof GetImageApiV2ImagesImageIdResponses];

export type PatchImageApiV2ImagesImageIdData = {
    body: UpdateMetaDataAndFileForm;
    path: {
        /**
         * Image_id of the image that needs to be fetched.
         */
        image_id: number;
    };
    query?: never;
    url: '/image-api/v2/images/{image_id}';
};

export type PatchImageApiV2ImagesImageIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PatchImageApiV2ImagesImageIdError = PatchImageApiV2ImagesImageIdErrors[keyof PatchImageApiV2ImagesImageIdErrors];

export type PatchImageApiV2ImagesImageIdResponses = {
    200: ImageMetaInformationV2DTO;
};

export type PatchImageApiV2ImagesImageIdResponse = PatchImageApiV2ImagesImageIdResponses[keyof PatchImageApiV2ImagesImageIdResponses];

export type GetImageApiV2ImagesExternalIdExternalIdData = {
    body?: never;
    path: {
        /**
         * External node id of the image that needs to be fetched.
         */
        external_id: string;
    };
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
    };
    url: '/image-api/v2/images/external_id/{external_id}';
};

export type GetImageApiV2ImagesExternalIdExternalIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetImageApiV2ImagesExternalIdExternalIdError = GetImageApiV2ImagesExternalIdExternalIdErrors[keyof GetImageApiV2ImagesExternalIdExternalIdErrors];

export type GetImageApiV2ImagesExternalIdExternalIdResponses = {
    200: ImageMetaInformationV2DTO;
};

export type GetImageApiV2ImagesExternalIdExternalIdResponse = GetImageApiV2ImagesExternalIdExternalIdResponses[keyof GetImageApiV2ImagesExternalIdExternalIdResponses];

export type DeleteImageApiV2ImagesImageIdLanguageLanguageData = {
    body?: never;
    path: {
        /**
         * Image_id of the image that needs to be fetched.
         */
        image_id: number;
        /**
         * The ISO 639-1 language code describing language.
         */
        language: string;
    };
    query?: never;
    url: '/image-api/v2/images/{image_id}/language/{language}';
};

export type DeleteImageApiV2ImagesImageIdLanguageLanguageErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type DeleteImageApiV2ImagesImageIdLanguageLanguageError = DeleteImageApiV2ImagesImageIdLanguageLanguageErrors[keyof DeleteImageApiV2ImagesImageIdLanguageLanguageErrors];

export type DeleteImageApiV2ImagesImageIdLanguageLanguageResponses = {
    200: ImageMetaInformationV2DTO;
    204: void;
};

export type DeleteImageApiV2ImagesImageIdLanguageLanguageResponse = DeleteImageApiV2ImagesImageIdLanguageLanguageResponses[keyof DeleteImageApiV2ImagesImageIdLanguageLanguageResponses];

export type GetImageApiV3ImagesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return only images with titles, alt-texts or tags matching the specified query.
         */
        query?: string;
        /**
         * Restrict query searches to the specified fields. If omitted or empty, all the fields are used.
         */
        'query-fields'?: Array<ImageSearchField>;
        /**
         * Return only images with full size larger than submitted value in bytes.
         */
        'minimum-size'?: number;
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * Fallback to existing language if language is specified.
         */
        fallback?: boolean;
        /**
         * Return only images with provided license. Specifying 'all' gives all images regardless of license.
         */
        license?: string;
        /**
         * Return copyrighted images. May be omitted.
         *
         * @deprecated
         */
        includeCopyrighted?: boolean;
        /**
         * The sorting used on results.
         * The following are supported: -relevance, relevance, -title, title, -lastUpdated, lastUpdated, -id, id, -width, width, -height, height.
         * Default is by -relevance (desc) when query is set, and title (asc) when query is empty.
         */
        sort?: string;
        /**
         * The page number of the search hits to display.
         */
        page?: number;
        /**
         * The number of search hits to display for each page. Defaults to 10 and max is 10000.
         */
        'page-size'?: number;
        /**
         * Filter images that are podcast friendly. Width==heigth and between 1400 and 3000.
         */
        'podcast-friendly'?: boolean;
        /**
         * A unique string obtained from a search you want to keep scrolling in. To obtain one from a search, provide one of the following values: [0,initial,start,first].
         * When scrolling, the parameters from the initial search is used, except in the case of 'language'.
         * This value may change between scrolls. Always use the one in the latest scroll result (The context, if unused, dies after 1m).
         * If you are not paginating past 10000 hits, you can ignore this and use 'page' and 'page-size' instead.
         *
         */
        'search-context'?: string;
        /**
         * Filter whether the image(s) should be model-released or not. Multiple values can be specified in a comma separated list. Possible values include: yes,no,not-applicable,not-set
         */
        'model-released'?: Array<ModelReleasedStatus>;
        /**
         * Filter whether the image(s) is AI generated or not. Multiple values can be specified in a comma separated list. Possible values include: Partial,Yes,No
         */
        'ai-generated'?: Array<AiGenerated>;
        /**
         * List of users to filter by.
         * The value to search for is the user-id from Auth0.
         * UpdatedBy on article and user in editorial-notes are searched.
         */
        users?: Array<string>;
        /**
         * Include inactive images
         */
        inactive?: boolean;
        /**
         * Filter images with width greater than or equal to this value.
         */
        'width-from'?: number;
        /**
         * Filter images with width less than or equal to this value.
         */
        'width-to'?: number;
        /**
         * Filter images with height greater than or equal to this value.
         */
        'height-from'?: number;
        /**
         * Filter images with height less than or equal to this value.
         */
        'height-to'?: number;
        /**
         * Filter images by content type (e.g., 'image/jpeg', 'image/png').
         */
        'content-type'?: string;
    };
    url: '/image-api/v3/images';
};

export type GetImageApiV3ImagesErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetImageApiV3ImagesError = GetImageApiV3ImagesErrors[keyof GetImageApiV3ImagesErrors];

export type GetImageApiV3ImagesResponses = {
    200: SearchResultV3DTO;
};

export type GetImageApiV3ImagesResponse = GetImageApiV3ImagesResponses[keyof GetImageApiV3ImagesResponses];

export type PostImageApiV3ImagesData = {
    body: MetaDataAndFileForm;
    path?: never;
    query?: never;
    url: '/image-api/v3/images';
};

export type PostImageApiV3ImagesErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PostImageApiV3ImagesError = PostImageApiV3ImagesErrors[keyof PostImageApiV3ImagesErrors];

export type PostImageApiV3ImagesResponses = {
    200: ImageMetaInformationV3DTO;
};

export type PostImageApiV3ImagesResponse = PostImageApiV3ImagesResponses[keyof PostImageApiV3ImagesResponses];

export type GetImageApiV3ImagesIdsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return only images that have one of the provided ids. To provide multiple ids, separate by comma (,).
         */
        ids?: Array<number>;
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
    };
    url: '/image-api/v3/images/ids';
};

export type GetImageApiV3ImagesIdsErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetImageApiV3ImagesIdsError = GetImageApiV3ImagesIdsErrors[keyof GetImageApiV3ImagesIdsErrors];

export type GetImageApiV3ImagesIdsResponses = {
    200: Array<ImageMetaInformationV3DTO>;
};

export type GetImageApiV3ImagesIdsResponse = GetImageApiV3ImagesIdsResponses[keyof GetImageApiV3ImagesIdsResponses];

export type GetImageApiV3ImagesTagSearchData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return only images with titles, alt-texts or tags matching the specified query.
         */
        query?: string;
        /**
         * The number of search hits to display for each page. Defaults to 10 and max is 10000.
         */
        'page-size'?: number;
        /**
         * The page number of the search hits to display.
         */
        page?: number;
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
        /**
         * The sorting used on results.
         * The following are supported: -relevance, relevance, -title, title, -lastUpdated, lastUpdated, -id, id, -width, width, -height, height.
         * Default is by -relevance (desc) when query is set, and title (asc) when query is empty.
         */
        sort?: string;
    };
    url: '/image-api/v3/images/tag-search';
};

export type GetImageApiV3ImagesTagSearchErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetImageApiV3ImagesTagSearchError = GetImageApiV3ImagesTagSearchErrors[keyof GetImageApiV3ImagesTagSearchErrors];

export type GetImageApiV3ImagesTagSearchResponses = {
    200: TagsSearchResultDTO;
};

export type GetImageApiV3ImagesTagSearchResponse = GetImageApiV3ImagesTagSearchResponses[keyof GetImageApiV3ImagesTagSearchResponses];

export type PostImageApiV3ImagesSearchData = {
    body: SearchParamsDTO;
    path?: never;
    query?: never;
    url: '/image-api/v3/images/search';
};

export type PostImageApiV3ImagesSearchErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PostImageApiV3ImagesSearchError = PostImageApiV3ImagesSearchErrors[keyof PostImageApiV3ImagesSearchErrors];

export type PostImageApiV3ImagesSearchResponses = {
    200: SearchResultV3DTO;
};

export type PostImageApiV3ImagesSearchResponse = PostImageApiV3ImagesSearchResponses[keyof PostImageApiV3ImagesSearchResponses];

export type DeleteImageApiV3ImagesImageIdData = {
    body?: never;
    path: {
        /**
         * Image_id of the image that needs to be fetched.
         */
        image_id: number;
    };
    query?: never;
    url: '/image-api/v3/images/{image_id}';
};

export type DeleteImageApiV3ImagesImageIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type DeleteImageApiV3ImagesImageIdError = DeleteImageApiV3ImagesImageIdErrors[keyof DeleteImageApiV3ImagesImageIdErrors];

export type DeleteImageApiV3ImagesImageIdResponses = {
    204: void;
};

export type DeleteImageApiV3ImagesImageIdResponse = DeleteImageApiV3ImagesImageIdResponses[keyof DeleteImageApiV3ImagesImageIdResponses];

export type GetImageApiV3ImagesImageIdData = {
    body?: never;
    path: {
        /**
         * Image_id of the image that needs to be fetched.
         */
        image_id: number;
    };
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
    };
    url: '/image-api/v3/images/{image_id}';
};

export type GetImageApiV3ImagesImageIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetImageApiV3ImagesImageIdError = GetImageApiV3ImagesImageIdErrors[keyof GetImageApiV3ImagesImageIdErrors];

export type GetImageApiV3ImagesImageIdResponses = {
    200: ImageMetaInformationV3DTO;
};

export type GetImageApiV3ImagesImageIdResponse = GetImageApiV3ImagesImageIdResponses[keyof GetImageApiV3ImagesImageIdResponses];

export type PatchImageApiV3ImagesImageIdData = {
    body: UpdateMetaDataAndFileForm;
    path: {
        /**
         * Image_id of the image that needs to be fetched.
         */
        image_id: number;
    };
    query?: never;
    url: '/image-api/v3/images/{image_id}';
};

export type PatchImageApiV3ImagesImageIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PatchImageApiV3ImagesImageIdError = PatchImageApiV3ImagesImageIdErrors[keyof PatchImageApiV3ImagesImageIdErrors];

export type PatchImageApiV3ImagesImageIdResponses = {
    200: ImageMetaInformationV3DTO;
};

export type PatchImageApiV3ImagesImageIdResponse = PatchImageApiV3ImagesImageIdResponses[keyof PatchImageApiV3ImagesImageIdResponses];

export type GetImageApiV3ImagesExternalIdExternalIdData = {
    body?: never;
    path: {
        /**
         * External node id of the image that needs to be fetched.
         */
        external_id: string;
    };
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
    };
    url: '/image-api/v3/images/external_id/{external_id}';
};

export type GetImageApiV3ImagesExternalIdExternalIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetImageApiV3ImagesExternalIdExternalIdError = GetImageApiV3ImagesExternalIdExternalIdErrors[keyof GetImageApiV3ImagesExternalIdExternalIdErrors];

export type GetImageApiV3ImagesExternalIdExternalIdResponses = {
    200: ImageMetaInformationV3DTO;
};

export type GetImageApiV3ImagesExternalIdExternalIdResponse = GetImageApiV3ImagesExternalIdExternalIdResponses[keyof GetImageApiV3ImagesExternalIdExternalIdResponses];

export type DeleteImageApiV3ImagesImageIdLanguageLanguageData = {
    body?: never;
    path: {
        /**
         * Image_id of the image that needs to be fetched.
         */
        image_id: number;
        /**
         * The ISO 639-1 language code describing language.
         */
        language: string;
    };
    query?: never;
    url: '/image-api/v3/images/{image_id}/language/{language}';
};

export type DeleteImageApiV3ImagesImageIdLanguageLanguageErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type DeleteImageApiV3ImagesImageIdLanguageLanguageError = DeleteImageApiV3ImagesImageIdLanguageLanguageErrors[keyof DeleteImageApiV3ImagesImageIdLanguageLanguageErrors];

export type DeleteImageApiV3ImagesImageIdLanguageLanguageResponses = {
    200: ImageMetaInformationV3DTO;
    204: void;
};

export type DeleteImageApiV3ImagesImageIdLanguageLanguageResponse = DeleteImageApiV3ImagesImageIdLanguageLanguageResponses[keyof DeleteImageApiV3ImagesImageIdLanguageLanguageResponses];

export type PostImageApiV3ImagesImageIdCopyData = {
    body: CopyMetaDataAndFileForm;
    path: {
        /**
         * Image_id of the image that needs to be fetched.
         */
        image_id: number;
    };
    query?: {
        /**
         * The ISO 639-1 language code describing language.
         */
        language?: string;
    };
    url: '/image-api/v3/images/{image_id}/copy';
};

export type PostImageApiV3ImagesImageIdCopyErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PostImageApiV3ImagesImageIdCopyError = PostImageApiV3ImagesImageIdCopyErrors[keyof PostImageApiV3ImagesImageIdCopyErrors];

export type PostImageApiV3ImagesImageIdCopyResponses = {
    200: ImageMetaInformationV3DTO;
};

export type PostImageApiV3ImagesImageIdCopyResponse = PostImageApiV3ImagesImageIdCopyResponses[keyof PostImageApiV3ImagesImageIdCopyResponses];

export type GetImageApiV3ImagesUsersEditorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/image-api/v3/images/users/editors';
};

export type GetImageApiV3ImagesUsersEditorsErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetImageApiV3ImagesUsersEditorsError = GetImageApiV3ImagesUsersEditorsErrors[keyof GetImageApiV3ImagesUsersEditorsErrors];

export type GetImageApiV3ImagesUsersEditorsResponses = {
    200: ImageEditorsDTO;
};

export type GetImageApiV3ImagesUsersEditorsResponse = GetImageApiV3ImagesUsersEditorsResponses[keyof GetImageApiV3ImagesUsersEditorsResponses];

export type GetImageApiRawIdImageIdData = {
    body?: never;
    headers?: {
        /**
         * Your app-key. May be omitted to access api anonymously, but rate limiting may apply on anonymous access.
         */
        'app-key'?: string;
    };
    path: {
        /**
         * The ID of the image
         */
        image_id: number;
    };
    query?: {
        /**
         * The target width to resize the image (the unit is pixles). Image proportions are kept intact
         */
        width?: number;
        /**
         * The target height to resize the image (the unit is pixles). Image proportions are kept intact
         */
        height?: number;
        /**
         * The first image coordinate X, in percent (0 to 100) or pixels depending on cropUnit, specifying the crop start position. If used the other crop parameters must also be supplied
         */
        cropStartX?: number;
        /**
         * The first image coordinate Y, in percent (0 to 100) or pixels depending on cropUnit, specifying the crop start position. If used the other crop parameters must also be supplied
         */
        cropStartY?: number;
        /**
         * The end image coordinate X, in percent (0 to 100) or pixels depending on cropUnit, specifying the crop end position. If used the other crop parameters must also be supplied
         */
        cropEndX?: number;
        /**
         * The end image coordinate Y, in percent (0 to 100) or pixels depending on cropUnit, specifying the crop end position. If used the other crop parameters must also be supplied
         */
        cropEndY?: number;
        /**
         * The unit of the crop parameters. Can be either 'percent' or 'pixel'. If omitted the unit is assumed to be 'percent'
         */
        cropUnit?: string;
        /**
         * The end image coordinate X, in percent (0 to 100), specifying the focal point. If used the other focal point parameter, width and/or height, must also be supplied
         */
        focalX?: number;
        /**
         * The end image coordinate Y, in percent (0 to 100), specifying the focal point. If used the other focal point parameter, width and/or height, must also be supplied
         */
        focalY?: number;
        /**
         * The wanted aspect ratio, defined as width/height. To be used together with the focal parameters. If used the width and height is ignored and derived from the aspect ratio instead.
         */
        ratio?: number;
        /**
         * The wanted aspect ratio, defined as width/height. To be used together with the focal parameters. If used the width and height is ignored and derived from the aspect ratio instead.
         */
        language?: string;
        /**
         * Whether the image should be downloaded or not. Only the presence of this parameter is needed.
         */
        download?: string;
    };
    url: '/image-api/raw/id/{image_id}';
};

export type GetImageApiRawIdImageIdErrors = {
    400: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetImageApiRawIdImageIdError = GetImageApiRawIdImageIdErrors[keyof GetImageApiRawIdImageIdErrors];

export type GetImageApiRawIdImageIdResponses = {
    200: Blob | File;
};

export type GetImageApiRawIdImageIdResponse = GetImageApiRawIdImageIdResponses[keyof GetImageApiRawIdImageIdResponses];

export type GetImageApiRawImageNameData = {
    body?: never;
    headers?: {
        /**
         * Your app-key. May be omitted to access api anonymously, but rate limiting may apply on anonymous access.
         */
        'app-key'?: string;
    };
    path: {
        /**
         * The name of the image
         */
        image_name: string;
    };
    query?: {
        /**
         * The target width to resize the image (the unit is pixles). Image proportions are kept intact
         */
        width?: number;
        /**
         * The target height to resize the image (the unit is pixles). Image proportions are kept intact
         */
        height?: number;
        /**
         * The first image coordinate X, in percent (0 to 100) or pixels depending on cropUnit, specifying the crop start position. If used the other crop parameters must also be supplied
         */
        cropStartX?: number;
        /**
         * The first image coordinate Y, in percent (0 to 100) or pixels depending on cropUnit, specifying the crop start position. If used the other crop parameters must also be supplied
         */
        cropStartY?: number;
        /**
         * The end image coordinate X, in percent (0 to 100) or pixels depending on cropUnit, specifying the crop end position. If used the other crop parameters must also be supplied
         */
        cropEndX?: number;
        /**
         * The end image coordinate Y, in percent (0 to 100) or pixels depending on cropUnit, specifying the crop end position. If used the other crop parameters must also be supplied
         */
        cropEndY?: number;
        /**
         * The unit of the crop parameters. Can be either 'percent' or 'pixel'. If omitted the unit is assumed to be 'percent'
         */
        cropUnit?: string;
        /**
         * The end image coordinate X, in percent (0 to 100), specifying the focal point. If used the other focal point parameter, width and/or height, must also be supplied
         */
        focalX?: number;
        /**
         * The end image coordinate Y, in percent (0 to 100), specifying the focal point. If used the other focal point parameter, width and/or height, must also be supplied
         */
        focalY?: number;
        /**
         * The wanted aspect ratio, defined as width/height. To be used together with the focal parameters. If used the width and height is ignored and derived from the aspect ratio instead.
         */
        ratio?: number;
        /**
         * The wanted aspect ratio, defined as width/height. To be used together with the focal parameters. If used the width and height is ignored and derived from the aspect ratio instead.
         */
        language?: string;
        /**
         * Whether the image should be downloaded or not. Only the presence of this parameter is needed.
         */
        download?: string;
    };
    url: '/image-api/raw/{image_name}';
};

export type GetImageApiRawImageNameErrors = {
    400: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetImageApiRawImageNameError = GetImageApiRawImageNameErrors[keyof GetImageApiRawImageNameErrors];

export type GetImageApiRawImageNameResponses = {
    200: Blob | File;
};

export type GetImageApiRawImageNameResponse = GetImageApiRawImageNameResponses[keyof GetImageApiRawImageNameResponses];

export type GetImageApiRawImageNameVariantSizeData = {
    body?: never;
    path: {
        /**
         * The name of the image (without file extension)
         */
        image_name: string;
        /**
         * Image variant size (with file extension)
         */
        variant_size: string;
    };
    query?: never;
    url: '/image-api/raw/{image_name}/{variant_size}';
};

export type GetImageApiRawImageNameVariantSizeErrors = {
    400: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type GetImageApiRawImageNameVariantSizeError = GetImageApiRawImageNameVariantSizeErrors[keyof GetImageApiRawImageNameVariantSizeErrors];

export type GetImageApiRawImageNameVariantSizeResponses = {
    200: Blob | File;
};

export type GetImageApiRawImageNameVariantSizeResponse = GetImageApiRawImageNameVariantSizeResponses[keyof GetImageApiRawImageNameVariantSizeResponses];

export type PostImageApiV1BulkData = {
    body: BatchMetaDataAndFileForm;
    path?: never;
    query?: never;
    url: '/image-api/v1/bulk';
};

export type PostImageApiV1BulkErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    default: AllErrors;
};

export type PostImageApiV1BulkError = PostImageApiV1BulkErrors[keyof PostImageApiV1BulkErrors];

export type PostImageApiV1BulkResponses = {
    200: BulkUploadStartedDTO;
};

export type PostImageApiV1BulkResponse = PostImageApiV1BulkResponses[keyof PostImageApiV1BulkResponses];

export type GetImageApiV1BulkStatusUploadIdData = {
    body?: never;
    path: {
        'upload-id': string;
    };
    query?: never;
    url: '/image-api/v1/bulk/status/{upload-id}';
};

export type GetImageApiV1BulkStatusUploadIdErrors = {
    400: AllErrors;
    401: AllErrors;
    403: AllErrors;
    404: AllErrors;
    500: AllErrors;
    default: AllErrors;
};

export type GetImageApiV1BulkStatusUploadIdError = GetImageApiV1BulkStatusUploadIdErrors[keyof GetImageApiV1BulkStatusUploadIdErrors];

export type GetImageApiV1BulkStatusUploadIdResponses = {
    200: BulkUploadStateDTO;
};

export type GetImageApiV1BulkStatusUploadIdResponse = GetImageApiV1BulkStatusUploadIdResponses[keyof GetImageApiV1BulkStatusUploadIdResponses];
