name: "Release: api-documentation"
on:
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - main
    paths:
      - frontend/api-documentation/**
      - frontend/package.json
      - frontend/pnpm-lock.yaml
      - frontend/nx.json
      - frontend/pnpm-workspace.yaml
jobs:
  release:
    uses: ndlano/reusable-workflows/.github/workflows/release.yaml@main
    secrets: inherit
    with:
      component: api-documentation
