/**
 * Copyright (c) 2026-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
// Source: RemixIcon
// License: Remix Icon License v1.0
import type { JSX } from "react";
import { Icon, type Props } from "../Icon";
export const BroadcastLine = (props: Props): JSX.Element => (
  <Icon fill="currentColor" viewBox="0 0 24 24" {...props}>
    <path d="m4.93 2.93 1.41 1.41A8 8 0 0 0 4 10c0 2.21.9 4.21 2.34 5.66l-1.41 1.41A10 10 0 0 1 2 10a10 10 0 0 1 2.93-7.07m14.14 0A10 10 0 0 1 22 10a10 10 0 0 1-2.93 7.07l-1.41-1.41A8 8 0 0 0 20 10c0-2.21-.9-4.21-2.34-5.66zM7.76 5.76l1.41 1.41A4 4 0 0 0 8 10c0 1.1.45 2.1 1.17 2.83l-1.41 1.41A6 6 0 0 1 6 10c0-1.66.67-3.16 1.76-4.24m8.48 0A6 6 0 0 1 18 10a6 6 0 0 1-1.76 4.24l-1.41-1.41A4 4 0 0 0 16 10a4 4 0 0 0-1.17-2.83zM12 12a2 2 0 1 1 0-4 2 2 0 0 1 0 4m-1 2h2v8h-2z" />
  </Icon>
);
