/**
 * Copyright (c) 2026-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
// Source: RemixIcon
// License: Remix Icon License v1.0
import type { JSX } from "react";
import { Icon, type Props } from "../Icon";
export const SettingsFill = (props: Props): JSX.Element => (
  <Icon fill="currentColor" viewBox="0 0 24 24" {...props}>
    <path d="M5.33 4.55A10 10 0 0 1 8.88 2.5 4 4 0 0 0 12 4a4 4 0 0 0 3.12-1.5 10 10 0 0 1 3.55 2.05A4 4 0 0 0 18.93 8a4 4 0 0 0 2.86 1.96 10 10 0 0 1 0 4.08A4 4 0 0 0 18.93 16a4 4 0 0 0-.26 3.46 10 10 0 0 1-3.55 2.04A4 4 0 0 0 12 20a4 4 0 0 0-3.12 1.5 10 10 0 0 1-3.55-2.04A4 4 0 0 0 5.07 16a4 4 0 0 0-2.86-1.95 10 10 0 0 1 0-4.1A4 4 0 0 0 5.07 8a4 4 0 0 0 .26-3.45M13.5 14.6a3 3 0 1 0-3-5.2 3 3 0 0 0 3 5.2" />
  </Icon>
);
